var searchData=
[
  ['iactivestate_0',['IActiveState',['../interface_oculus_1_1_interaction_1_1_i_active_state.html',1,'Oculus::Interaction']]],
  ['iactivestatemodel_1',['IActiveStateModel',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_model.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iactivestatenodeui_2',['IActiveStateNodeUI',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_node_u_i.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iactivestatetreenode_3',['IActiveStateTreeNode',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_tree_node.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iapmanager_4',['IAPManager',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_board_game_1_1_i_a_p_manager.html',1,'Oculus::Platform::Samples::VrBoardGame']]],
  ['iapplicationdetailprovider_5',['IApplicationDetailProvider',['../interface_meta_1_1_wit_ai_1_1_data_1_1_configuration_1_1_i_application_detail_provider.html',1,'Meta::WitAi::Data::Configuration']]],
  ['iapstatus_6',['IapStatus',['../class_oculus_1_1_platform_1_1_models_1_1_asset_details.html#a4c69dfe09d63af0ff4fb04872494badc',1,'Oculus::Platform::Models::AssetDetails']]],
  ['iaudioeventprovider_7',['IAudioEventProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_event_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['iaudioinputevents_8',['IAudioInputEvents',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_input_events.html',1,'Meta::WitAi::Interfaces']]],
  ['iaudioinputsource_9',['IAudioInputSource',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_input_source.html',1,'Meta::WitAi::Interfaces']]],
  ['iaxis1d_10',['IAxis1D',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_axis1_d.html',1,'Oculus::Interaction::Input']]],
  ['iaxis2d_11',['IAxis2D',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_axis2_d.html',1,'Oculus::Interaction::Input']]],
  ['ibounds_12',['IBounds',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_bounds.html',1,'Oculus::Interaction::Surfaces']]],
  ['iboundsclipper_13',['IBoundsClipper',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_bounds_clipper.html',1,'Oculus::Interaction::Surfaces']]],
  ['ibutton_14',['IButton',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_button.html',1,'Oculus::Interaction::Input']]],
  ['icandidatecomparer_15',['ICandidateComparer',['../interface_oculus_1_1_interaction_1_1_i_candidate_comparer.html',1,'Oculus::Interaction']]],
  ['icandidateposition_16',['ICandidatePosition',['../interface_oculus_1_1_interaction_1_1_i_candidate_position.html',1,'Oculus::Interaction']]],
  ['iclippedsurface_17',['IClippedSurface',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['iclippedsurface_3c_20iboundsclipper_20_3e_18',['IClippedSurface&lt; IBoundsClipper &gt;',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['iclippedsurface_3c_20icylinderclipper_20_3e_19',['IClippedSurface&lt; ICylinderClipper &gt;',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['icollidersref_20',['ICollidersRef',['../interface_oculus_1_1_interaction_1_1_i_colliders_ref.html',1,'Oculus::Interaction']]],
  ['iconnection_21',['IConnection',['../interface_oculus_1_1_voice_1_1_core_1_1_bindings_1_1_interfaces_1_1_i_connection.html',1,'Oculus::Voice::Core::Bindings::Interfaces']]],
  ['icontroller_22',['IController',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_controller.html',1,'Oculus::Interaction::Input']]],
  ['icontrollerdatamodifier_23',['IControllerDataModifier',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_controller_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_24',['ICopyFrom',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20controllerdataasset_20_3e_25',['ICopyFrom&lt; ControllerDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20handdataasset_20_3e_26',['ICopyFrom&lt; HandDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20hmddataasset_20_3e_27',['ICopyFrom&lt; HmdDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icurvedplane_28',['ICurvedPlane',['../interface_oculus_1_1_interaction_1_1_i_curved_plane.html',1,'Oculus::Interaction']]],
  ['icylinderclipper_29',['ICylinderClipper',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_cylinder_clipper.html',1,'Oculus::Interaction::Surfaces']]],
  ['id_30',['id',['../struct_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_trait_value_info.html#af103971a8cff3e3330e8a6cef1af9bfb',1,'Meta::WitAi::Data::Info::WitTraitValueInfo']]],
  ['id_31',['ID',['../class_oculus_1_1_platform_1_1_models_1_1_cal_application_finalized.html#a7fdcadfc075fcea11c293be797584908',1,'Oculus.Platform.Models.CalApplicationFinalized.ID()'],['../class_oculus_1_1_platform_1_1_models_1_1_cal_application_suggestion.html#aa9b62f8544f9dd743a0d7740a4e4030b',1,'Oculus.Platform.Models.CalApplicationSuggestion.ID()'],['../class_oculus_1_1_platform_1_1_models_1_1_room_invite_notification.html#ad10ac0ffe015f7061856b8ff455831fe',1,'Oculus.Platform.Models.RoomInviteNotification.ID()'],['../class_meta_1_1_conduit_1_1_conduit_entity_attribute.html#a49f622311f0d3cd0f161096e8fcd0900',1,'Meta.Conduit.ConduitEntityAttribute.ID()'],['../class_oculus_1_1_platform_1_1_models_1_1_room.html#af84a34831339c558c75ba25525086b23',1,'Oculus.Platform.Models.Room.ID()']]],
  ['id_32',['Id',['../class_oculus_1_1_platform_1_1_models_1_1_blocked_user.html#a31b79dad642b2539281b77de4b89288d',1,'Oculus.Platform.Models.BlockedUser.Id()'],['../struct_o_v_r_space_user.html#a26355d951a6de7ba78930cb30548e873',1,'OVRSpaceUser.Id()']]],
  ['id_33',['id',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_visuals_1_1_hand_joint_map.html#ac33d209b9da2ecfcd90278f66959ffe1',1,'Oculus.Interaction.HandGrab.Visuals.HandJointMap.id()'],['../struct_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_app_info.html#a70c11314e4f65955c82b2cfb530b1a30',1,'Meta.WitAi.Data.Info.WitAppInfo.id()'],['../struct_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_entity_info.html#a3e1fdc3cb2110ea936776d3afd71700f',1,'Meta.WitAi.Data.Info.WitEntityInfo.id()'],['../struct_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_entity_role_info.html#a49c2776dda6e87c9792776963303c285',1,'Meta.WitAi.Data.Info.WitEntityRoleInfo.id()'],['../struct_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_intent_entity_info.html#a561398d0439f802954a17f725ea3ec75',1,'Meta.WitAi.Data.Info.WitIntentEntityInfo.id()'],['../struct_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_intent_info.html#ad1754257593c0d285c63a9492a216bf8',1,'Meta.WitAi.Data.Info.WitIntentInfo.id()'],['../class_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_trait_info.html#aaf37311ff95a9450a9eab675ed01ddf7',1,'Meta.WitAi.Data.Info.WitTraitInfo.id()']]],
  ['idatasource_34',['IDataSource',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_data_source.html',1,'Oculus::Interaction::Input']]],
  ['identity_35',['identity',['../struct_o_v_r_pose.html#ab1fe1f6d36ab555296ca5de73e485d6e',1,'OVRPose']]],
  ['idictationservice_36',['IDictationService',['../interface_meta_1_1_wit_ai_1_1_dictation_1_1_i_dictation_service.html',1,'Meta::WitAi::Dictation']]],
  ['idistanceinteractor_37',['IDistanceInteractor',['../interface_oculus_1_1_interaction_1_1_i_distance_interactor.html',1,'Oculus::Interaction']]],
  ['idynamicentitiesprovider_38',['IDynamicEntitiesProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_dynamic_entities_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['ienumerablehashset_39',['IEnumerableHashSet',['../interface_oculus_1_1_interaction_1_1_collections_1_1_i_enumerable_hash_set.html',1,'Oculus::Interaction::Collections']]],
  ['ievent_40',['IEvent',['../interface_oculus_1_1_interaction_1_1_i_event.html',1,'Oculus::Interaction']]],
  ['ifeaturestatethreshold_41',['IFeatureStateThreshold',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_threshold.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethreshold_3c_20string_20_3e_42',['IFeatureStateThreshold&lt; string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_threshold.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_43',['IFeatureStateThresholds',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_3c_20fingerfeature_2c_20string_20_3e_44',['IFeatureStateThresholds&lt; FingerFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_3c_20transformfeature_2c_20string_20_3e_45',['IFeatureStateThresholds&lt; TransformFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_46',['IFeatureThresholds',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_3c_20fingerfeature_2c_20string_20_3e_47',['IFeatureThresholds&lt; FingerFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_3c_20transformfeature_2c_20string_20_3e_48',['IFeatureThresholds&lt; TransformFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifingerapi_49',['IFingerAPI',['../interface_oculus_1_1_interaction_1_1_i_finger_a_p_i.html',1,'Oculus::Interaction']]],
  ['ifingerfeaturestateprovider_50',['IFingerFeatureStateProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_finger_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifingeruseapi_51',['IFingerUseAPI',['../interface_oculus_1_1_interaction_1_1_i_finger_use_a_p_i.html',1,'Oculus::Interaction']]],
  ['igameobjectfilter_52',['IGameObjectFilter',['../interface_oculus_1_1_interaction_1_1_i_game_object_filter.html',1,'Oculus::Interaction']]],
  ['igrabbable_53',['IGrabbable',['../interface_oculus_1_1_interaction_1_1_i_grabbable.html',1,'Oculus::Interaction']]],
  ['igrabsurface_54',['IGrabSurface',['../interface_oculus_1_1_interaction_1_1_grab_1_1_grab_surfaces_1_1_i_grab_surface.html',1,'Oculus::Interaction::Grab::GrabSurfaces']]],
  ['ihand_55',['IHand',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand.html',1,'Oculus::Interaction::Input']]],
  ['ihandgrabbable_56',['IHandGrabbable',['../interface_oculus_1_1_interaction_1_1_grab_1_1_i_hand_grabbable.html',1,'Oculus::Interaction::Grab']]],
  ['ihandgrabber_57',['IHandGrabber',['../interface_oculus_1_1_interaction_1_1_grab_1_1_i_hand_grabber.html',1,'Oculus::Interaction::Grab']]],
  ['ihandgrabstate_58',['IHandGrabState',['../interface_oculus_1_1_interaction_1_1_hand_grab_1_1_i_hand_grab_state.html',1,'Oculus::Interaction::HandGrab']]],
  ['ihandgrabusedelegate_59',['IHandGrabUseDelegate',['../interface_oculus_1_1_interaction_1_1_hand_grab_1_1_i_hand_grab_use_delegate.html',1,'Oculus::Interaction::HandGrab']]],
  ['ihandskeletonprovider_60',['IHandSkeletonProvider',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand_skeleton_provider.html',1,'Oculus::Interaction::Input']]],
  ['ihandspheremap_61',['IHandSphereMap',['../interface_oculus_1_1_interaction_1_1_i_hand_sphere_map.html',1,'Oculus::Interaction']]],
  ['ihandvisual_62',['IHandVisual',['../interface_oculus_1_1_interaction_1_1_i_hand_visual.html',1,'Oculus::Interaction']]],
  ['ihmd_63',['IHmd',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hmd.html',1,'Oculus::Interaction::Input']]],
  ['iinteractable_64',['IInteractable',['../interface_oculus_1_1_interaction_1_1_i_interactable.html',1,'Oculus::Interaction']]],
  ['iinteractableview_65',['IInteractableView',['../interface_oculus_1_1_interaction_1_1_i_interactable_view.html',1,'Oculus::Interaction']]],
  ['iinteractor_66',['IInteractor',['../interface_oculus_1_1_interaction_1_1_i_interactor.html',1,'Oculus::Interaction']]],
  ['iinteractorview_67',['IInteractorView',['../interface_oculus_1_1_interaction_1_1_i_interactor_view.html',1,'Oculus::Interaction']]],
  ['ijointdeltaprovider_68',['IJointDeltaProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_joint_delta_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ijsondeserializer_69',['IJsonDeserializer',['../interface_meta_1_1_wit_ai_1_1_json_1_1_i_json_deserializer.html',1,'Meta::WitAi::Json']]],
  ['ijsonserializer_70',['IJsonSerializer',['../interface_meta_1_1_wit_ai_1_1_json_1_1_i_json_serializer.html',1,'Meta::WitAi::Json']]],
  ['ilocomotioneventbroadcaster_71',['ILocomotionEventBroadcaster',['../interface_oculus_1_1_interaction_1_1_locomotion_1_1_i_locomotion_event_broadcaster.html',1,'Oculus::Interaction::Locomotion']]],
  ['ilocomotioneventhandler_72',['ILocomotionEventHandler',['../interface_oculus_1_1_interaction_1_1_locomotion_1_1_i_locomotion_event_handler.html',1,'Oculus::Interaction::Locomotion']]],
  ['imicrophone_73',['IMicrophone',['../interface_oculus_1_1_platform_1_1_i_microphone.html',1,'Oculus::Platform']]],
  ['imovement_74',['IMovement',['../interface_oculus_1_1_interaction_1_1_i_movement.html',1,'Oculus::Interaction']]],
  ['imovementprovider_75',['IMovementProvider',['../interface_oculus_1_1_interaction_1_1_i_movement_provider.html',1,'Oculus::Interaction']]],
  ['impactaudio_76',['ImpactAudio',['../struct_oculus_1_1_interaction_1_1_impact_audio.html',1,'Oculus::Interaction']]],
  ['impostertocanvastransformpoint_77',['ImposterToCanvasTransformPoint',['../class_oculus_1_1_interaction_1_1_unity_canvas_1_1_canvas_mesh.html#a92b49ababf37c78373f4295dcc7a00f7',1,'Oculus::Interaction::UnityCanvas::CanvasMesh']]],
  ['imusample_5ft_78',['ImuSample_t',['../struct_o_v_r_1_1_open_v_r_1_1_imu_sample__t.html',1,'OVR::OpenVR']]],
  ['in_79',['In',['../class_oculus_1_1_interaction_1_1_surfaces_1_1_cylinder_surface.html#a15d7c5c286ea843ce46ead37721a42ceaefeb369cccbd560588a756610865664c',1,'Oculus::Interaction::Surfaces::CylinderSurface']]],
  ['indexpinchsafereleaseselector_80',['IndexPinchSafeReleaseSelector',['../class_oculus_1_1_interaction_1_1_index_pinch_safe_release_selector.html',1,'Oculus::Interaction']]],
  ['indexpinchselector_81',['IndexPinchSelector',['../class_oculus_1_1_interaction_1_1_index_pinch_selector.html',1,'Oculus::Interaction']]],
  ['init_82',['Init',['../class_o_v_r_1_1_open_v_r_1_1_open_v_r.html#ac8ba8e7c606dcb5e57ad393c9bf50925',1,'OVR.OpenVR.OpenVR.Init()'],['../class_o_v_r_1_1_audio_manager.html#a39f2e654e4a2ece3991e7092816bbb2d',1,'OVR.AudioManager.Init()'],['../class_o_v_r_lip_sync_debug_console.html#adece4ce4a6eb99278d671e138f8e7702',1,'OVRLipSyncDebugConsole.Init()']]],
  ['initconfigoptions_83',['InitConfigOptions',['../namespace_oculus_1_1_platform.html#a8d7b18b99f7b8f79e360fb0066fb202a',1,'Oculus::Platform']]],
  ['initializefrom_84',['InitializeFrom',['../class_o_v_r_scene_anchor.html#a48e7f550ed8a95461dfc87d34dc009b2',1,'OVRSceneAnchor']]],
  ['initializefromexisting_85',['InitializeFromExisting',['../class_o_v_r_spatial_anchor.html#a1a46dde6fe2c228fcb3d088db3d41883',1,'OVRSpatialAnchor']]],
  ['initializemicrophone_86',['InitializeMicrophone',['../class_o_v_r_lip_sync_mic_input.html#af506d3c985d6560043c710bb253ffff9',1,'OVRLipSyncMicInput']]],
  ['inituicomponent_87',['initUIComponent',['../class_o_v_r_debug_info.html#af8eb4d3233c62e3ea7cb199a4be92774',1,'OVRDebugInfo']]],
  ['inituicomponents_88',['InitUIComponents',['../class_o_v_r_debug_info.html#aef4d0e92c2acf06ac3390749d1dc030c',1,'OVRDebugInfo']]],
  ['inputanalogactiondata_5ft_89',['InputAnalogActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_analog_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputaxis_90',['InputAxis',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_axis.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputbutton_91',['InputButton',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_button.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputcode_92',['inputCode',['../class_o_v_r_platform_menu.html#a826854a2d72fef616ef123d15b66d75a',1,'OVRPlatformMenu']]],
  ['inputdigitalactiondata_5ft_93',['InputDigitalActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_digital_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputfocusacquired_94',['InputFocusAcquired',['../class_o_v_r_manager.html#a1a81f67a4ed67e392e0cbfbb1b459cda',1,'OVRManager']]],
  ['inputfocuslost_95',['InputFocusLost',['../class_o_v_r_manager.html#aff246573c412d4fa68c06cefbc72ea7e',1,'OVRManager']]],
  ['inputhandler_96',['InputHandler',['../class_locomotion_teleport.html#aa05d3e12214c8fe2bfb77694550ddc5d',1,'LocomotionTeleport']]],
  ['inputkey_97',['InputKey',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_key.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputmodes_98',['InputModes',['../class_teleport_input_handler_touch.html#ac79ffec142cdbec3b263740998fabecd',1,'TeleportInputHandlerTouch']]],
  ['inputmousebutton_99',['InputMouseButton',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_mouse_button.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputnodestate_100',['InputNodeState',['../struct_o_v_r_g_l_t_f_animatinon_node_1_1_input_node_state.html',1,'OVRGLTFAnimatinonNode']]],
  ['inputorigininfo_5ft_101',['InputOriginInfo_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_origin_info__t.html',1,'OVR::OpenVR']]],
  ['inputposeactiondata_5ft_102',['InputPoseActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_pose_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputskeletalactiondata_5ft_103',['InputSkeletalActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_skeletal_action_data__t.html',1,'OVR::OpenVR']]],
  ['insightpassthroughkeyboardhandsintensity_104',['InsightPassthroughKeyboardHandsIntensity',['../struct_o_v_r_plugin_1_1_insight_passthrough_keyboard_hands_intensity.html',1,'OVRPlugin']]],
  ['insightpassthroughstyle_105',['InsightPassthroughStyle',['../struct_o_v_r_plugin_1_1_insight_passthrough_style.html',1,'OVRPlugin']]],
  ['inspectorbuttonattribute_106',['InspectorButtonAttribute',['../class_oculus_1_1_interaction_1_1_inspector_button_attribute.html',1,'Oculus::Interaction']]],
  ['inspectorcommentattribute_107',['InspectorCommentAttribute',['../class_inspector_comment_attribute.html',1,'']]],
  ['inspectornoteattribute_108',['InspectorNoteAttribute',['../class_inspector_note_attribute.html',1,'']]],
  ['installedapplication_109',['InstalledApplication',['../class_oculus_1_1_platform_1_1_models_1_1_installed_application.html',1,'Oculus::Platform::Models']]],
  ['installedapplicationlist_110',['InstalledApplicationList',['../class_oculus_1_1_platform_1_1_models_1_1_installed_application_list.html',1,'Oculus::Platform::Models']]],
  ['instance_111',['instance',['../class_o_v_r_lip_sync_debug_console.html#a203a669e3380c2f4e87bc02b17399767',1,'OVRLipSyncDebugConsole.instance()'],['../class_o_v_r_manager.html#a10c7c50d4c6e83d28e5ceea4bab67e35',1,'OVRManager.instance()']]],
  ['instance_112',['Instance',['../class_meta_1_1_wit_ai_1_1_data_1_1_entities_1_1_dynamic_entity_keyword_registry.html#a5ee662336e5c4fcb1e7848b9f7910401',1,'Meta.WitAi.Data.Entities.DynamicEntityKeywordRegistry.Instance()'],['../class_anchor_u_i_manager.html#ab7a4d232ca955e9a85a190fe62cca30c',1,'AnchorUIManager.Instance()']]],
  ['instructions_113',['Instructions',['../class_oculus_1_1_voice_1_1_demo_1_1_u_i_shapes_demo_1_1_instructions.html',1,'Oculus::Voice::Demo::UIShapesDemo']]],
  ['intent_114',['intent',['../class_meta_1_1_wit_ai_1_1_callback_handlers_1_1_wit_intent_matcher.html#a3271098e1e56e23e52cd2ab572ce1e49',1,'Meta::WitAi::CallbackHandlers::WitIntentMatcher']]],
  ['intent_115',['Intent',['../class_meta_1_1_conduit_1_1_conduit_action_attribute.html#aef0e334981e83d52af4d3316b4facc08',1,'Meta::Conduit::ConduitActionAttribute']]],
  ['intents_116',['intents',['../struct_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_app_info.html#a19ad0e3691832e93a33e36df2b347f11',1,'Meta::WitAi::Data::Info::WitAppInfo']]],
  ['interactable_117',['Interactable',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus.Interaction.Interactable&lt; TInteractor, TInteractable &gt;'],['../class_oculus_sample_framework_1_1_interactable.html',1,'OculusSampleFramework.Interactable']]],
  ['interactable_3c_20handgrabuseinteractor_2c_20handgrabuseinteractable_20_3e_118',['Interactable&lt; HandGrabUseInteractor, HandGrabUseInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20locomotionaxisturnerinteractor_2c_20locomotionaxisturnerinteractable_20_3e_119',['Interactable&lt; LocomotionAxisTurnerInteractor, LocomotionAxisTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20locomotionturnerinteractor_2c_20locomotionturnerinteractable_20_3e_120',['Interactable&lt; LocomotionTurnerInteractor, LocomotionTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20snapinteractor_2c_20snapinteractable_20_3e_121',['Interactable&lt; SnapInteractor, SnapInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20teleportinteractor_2c_20teleportinteractable_20_3e_122',['Interactable&lt; TeleportInteractor, TeleportInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactablecollisiondepth_123',['InteractableCollisionDepth',['../namespace_oculus_sample_framework.html#a772810ffa57e1f179983ee4003a899a4',1,'OculusSampleFramework']]],
  ['interactablecollisioninfo_124',['InteractableCollisionInfo',['../class_oculus_sample_framework_1_1_interactable_collision_info.html',1,'OculusSampleFramework']]],
  ['interactablecolorvisual_125',['InteractableColorVisual',['../class_oculus_1_1_interaction_1_1_interactable_color_visual.html',1,'Oculus::Interaction']]],
  ['interactabledebugvisual_126',['InteractableDebugVisual',['../class_oculus_1_1_interaction_1_1_interactable_debug_visual.html',1,'Oculus::Interaction']]],
  ['interactablegroup_127',['InteractableGroup',['../class_oculus_1_1_interaction_1_1_interactable_group.html',1,'Oculus::Interaction']]],
  ['interactablegroupview_128',['InteractableGroupView',['../class_oculus_1_1_interaction_1_1_interactable_group_view.html',1,'Oculus::Interaction']]],
  ['interactablelimits_129',['InteractableLimits',['../struct_oculus_1_1_interaction_1_1_interactable_group_1_1_interactable_limits.html',1,'Oculus::Interaction::InteractableGroup']]],
  ['interactableregistry_130',['InteractableRegistry',['../class_oculus_1_1_interaction_1_1_interactable_registry.html',1,'Oculus.Interaction.InteractableRegistry&lt; TInteractor, TInteractable &gt;'],['../class_oculus_sample_framework_1_1_interactable_registry.html',1,'OculusSampleFramework.InteractableRegistry']]],
  ['interactablesdata_131',['InteractablesData',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_hand_grab_interactable_data_collection.html#af3a276132fbe01b74c2ce25a340ffa3d',1,'Oculus::Interaction::HandGrab::HandGrabInteractableDataCollection']]],
  ['interactableselected_132',['InteractableSelected',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_hand_grab_interactor.html#aa404e152e8c10431df37d122e5fa8629',1,'Oculus::Interaction::HandGrab::HandGrabInteractor']]],
  ['interactableset_133',['InteractableSet',['../struct_oculus_1_1_interaction_1_1_interactable_registry_1_1_interactable_set.html#af3b66876440f8cfc01dcc4dc89519112',1,'Oculus.Interaction.InteractableRegistry.InteractableSet.InteractableSet()'],['../struct_oculus_1_1_interaction_1_1_interactable_registry_1_1_interactable_set.html',1,'Oculus.Interaction.InteractableRegistry&lt; TInteractor, TInteractable &gt;.InteractableSet']]],
  ['interactablestateargs_134',['InteractableStateArgs',['../class_oculus_sample_framework_1_1_interactable_state_args.html',1,'OculusSampleFramework']]],
  ['interactablestateargsevent_135',['InteractableStateArgsEvent',['../class_oculus_sample_framework_1_1_interactable_1_1_interactable_state_args_event.html',1,'OculusSampleFramework::Interactable']]],
  ['interactablestatechangeargs_136',['InteractableStateChangeArgs',['../struct_oculus_1_1_interaction_1_1_interactable_state_change_args.html',1,'Oculus::Interaction']]],
  ['interactabletool_137',['InteractableTool',['../class_oculus_sample_framework_1_1_interactable_tool.html',1,'OculusSampleFramework']]],
  ['interactabletoolscreator_138',['InteractableToolsCreator',['../class_oculus_sample_framework_1_1_interactable_tools_creator.html',1,'OculusSampleFramework']]],
  ['interactabletoolsinputrouter_139',['InteractableToolsInputRouter',['../class_oculus_sample_framework_1_1_interactable_tools_input_router.html',1,'OculusSampleFramework']]],
  ['interactabletooltags_140',['InteractableToolTags',['../namespace_oculus_sample_framework.html#a7e741d13e3dd02c4734118cf32889e5f',1,'OculusSampleFramework']]],
  ['interactabletoolview_141',['InteractableToolView',['../interface_oculus_sample_framework_1_1_interactable_tool_view.html',1,'OculusSampleFramework']]],
  ['interactabletriggerbroadcaster_142',['InteractableTriggerBroadcaster',['../class_oculus_1_1_interaction_1_1_interactable_trigger_broadcaster.html',1,'Oculus::Interaction']]],
  ['interactableunityeventwrapper_143',['InteractableUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_interactable_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['interactableunselected_144',['InteractableUnselected',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_hand_grab_interactor.html#ae8ba1a7c028b68b8133e2e09ffe8a953',1,'Oculus::Interaction::HandGrab::HandGrabInteractor']]],
  ['interactionhandler_145',['InteractionHandler',['../class_oculus_1_1_voice_1_1_demo_1_1_interaction_handler.html',1,'Oculus::Voice::Demo']]],
  ['interactionposition_146',['InteractionPosition',['../class_oculus_sample_framework_1_1_interactable_tool.html#ad37bc7ae14bb3d7268c4dc469a07b3c0',1,'OculusSampleFramework::InteractableTool']]],
  ['interactor_147',['Interactor',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20handgrabuseinteractor_2c_20handgrabuseinteractable_20_3e_148',['Interactor&lt; HandGrabUseInteractor, HandGrabUseInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20locomotionaxisturnerinteractor_2c_20locomotionaxisturnerinteractable_20_3e_149',['Interactor&lt; LocomotionAxisTurnerInteractor, LocomotionAxisTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20locomotionturnerinteractor_2c_20locomotionturnerinteractable_20_3e_150',['Interactor&lt; LocomotionTurnerInteractor, LocomotionTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20snapinteractor_2c_20snapinteractable_20_3e_151',['Interactor&lt; SnapInteractor, SnapInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20teleportinteractor_2c_20teleportinteractable_20_3e_152',['Interactor&lt; TeleportInteractor, TeleportInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactoractivestate_153',['InteractorActiveState',['../class_oculus_1_1_interaction_1_1_interactor_active_state.html',1,'Oculus::Interaction']]],
  ['interactordebugvisual_154',['InteractorDebugVisual',['../class_oculus_1_1_interaction_1_1_interactor_debug_visual.html',1,'Oculus::Interaction']]],
  ['interactorgroup_155',['InteractorGroup',['../class_oculus_1_1_interaction_1_1_interactor_group.html',1,'Oculus::Interaction']]],
  ['interactorreticle_156',['InteractorReticle',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledataghost_20_3e_157',['InteractorReticle&lt; ReticleDataGhost &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledataicon_20_3e_158',['InteractorReticle&lt; ReticleDataIcon &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledatamesh_20_3e_159',['InteractorReticle&lt; ReticleDataMesh &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledatateleport_20_3e_160',['InteractorReticle&lt; ReticleDataTeleport &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorstatechangeargs_161',['InteractorStateChangeArgs',['../struct_oculus_1_1_interaction_1_1_interactor_state_change_args.html',1,'Oculus::Interaction']]],
  ['interactorunityeventwrapper_162',['InteractorUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_interactor_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['interfaceattribute_163',['InterfaceAttribute',['../class_oculus_1_1_interaction_1_1_interface_attribute.html#a8687dd730627c475fda040d7d613437f',1,'Oculus.Interaction.InterfaceAttribute.InterfaceAttribute()'],['../class_oculus_1_1_interaction_1_1_interface_attribute.html',1,'Oculus.Interaction.InterfaceAttribute']]],
  ['interfacedrawer_164',['InterfaceDrawer',['../class_oculus_1_1_interaction_1_1_interface_support_1_1_interface_drawer.html',1,'Oculus::Interaction::InterfaceSupport']]],
  ['interfacepicker_165',['InterfacePicker',['../class_oculus_1_1_interaction_1_1_interface_support_1_1_interface_picker.html',1,'Oculus::Interaction::InterfaceSupport']]],
  ['interpolationcache_166',['InterpolationCache',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_grab_pose_finder_1_1_interpolation_cache.html',1,'Oculus::Interaction::HandGrab::GrabPoseFinder']]],
  ['intersectionmaskcircle_5ft_167',['IntersectionMaskCircle_t',['../struct_o_v_r_1_1_open_v_r_1_1_intersection_mask_circle__t.html',1,'OVR::OpenVR']]],
  ['intersectionmaskrectangle_5ft_168',['IntersectionMaskRectangle_t',['../struct_o_v_r_1_1_open_v_r_1_1_intersection_mask_rectangle__t.html',1,'OVR::OpenVR']]],
  ['inverse_169',['Inverse',['../struct_o_v_r_pose.html#acd28049398308ccc5947e2c92964a906',1,'OVRPose']]],
  ['invite_170',['Invite',['../struct_oculus_1_1_platform_1_1_samples_1_1_vr_voice_chat_1_1_room_manager_1_1_invite.html',1,'Oculus::Platform::Samples::VrVoiceChat::RoomManager']]],
  ['invitedusers_171',['InvitedUsers',['../class_oculus_1_1_platform_1_1_models_1_1_launch_invite_panel_flow_result.html#aaed4018ef54268baf79fa0ebf720c4fa',1,'Oculus::Platform::Models::LaunchInvitePanelFlowResult']]],
  ['invitedusersoptional_172',['InvitedUsersOptional',['../class_oculus_1_1_platform_1_1_models_1_1_room.html#aad9f6efb83f3fb3d8a054873e0ef392b',1,'Oculus::Platform::Models::Room']]],
  ['inviteonly_173',['InviteOnly',['../namespace_oculus_1_1_platform.html#a1061597ec07ba8a3def037ee4cd13640a78b0afc0ca909ab6dad3892b5ebd259e',1,'Oculus::Platform']]],
  ['inviteoptions_174',['InviteOptions',['../class_oculus_1_1_platform_1_1_invite_options.html',1,'Oculus::Platform']]],
  ['invitepanelresultinfo_175',['InvitePanelResultInfo',['../class_oculus_1_1_platform_1_1_models_1_1_invite_panel_result_info.html',1,'Oculus::Platform::Models']]],
  ['invites_176',['Invites',['../class_oculus_1_1_platform_1_1_models_1_1_send_invites_result.html#a12aca749928e56a110c2d3276dfcec4c',1,'Oculus::Platform::Models::SendInvitesResult']]],
  ['invitessent_177',['InvitesSent',['../class_oculus_1_1_platform_1_1_models_1_1_invite_panel_result_info.html#a318ba578d570897b73e81b83909c1558',1,'Oculus::Platform::Models::InvitePanelResultInfo']]],
  ['invitetoken_178',['InviteToken',['../class_oculus_1_1_platform_1_1_models_1_1_user.html#ad1b97d275ff358d9811faa28cfd3b3fa',1,'Oculus::Platform::Models::User']]],
  ['ioneeurofilter_179',['IOneEuroFilter',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20float_20_3e_180',['IOneEuroFilter&lt; float &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20quaternion_20_3e_181',['IOneEuroFilter&lt; Quaternion &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20vector3_20_3e_182',['IOneEuroFilter&lt; Vector3 &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['iovrcamerarigref_183',['IOVRCameraRigRef',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_o_v_r_camera_rig_ref.html',1,'Oculus::Interaction::Input']]],
  ['iovrmeshdataprovider_184',['IOVRMeshDataProvider',['../interface_o_v_r_mesh_1_1_i_o_v_r_mesh_data_provider.html',1,'OVRMesh']]],
  ['iovrmeshrendererdataprovider_185',['IOVRMeshRendererDataProvider',['../interface_o_v_r_mesh_renderer_1_1_i_o_v_r_mesh_renderer_data_provider.html',1,'OVRMeshRenderer']]],
  ['iovrplugininfosupplier_186',['IOVRPluginInfoSupplier',['../interface_oculus_1_1_v_r_1_1_editor_1_1_i_o_v_r_plugin_info_supplier.html',1,'Oculus::VR::Editor']]],
  ['iovrskeletondataprovider_187',['IOVRSkeletonDataProvider',['../interface_o_v_r_skeleton_1_1_i_o_v_r_skeleton_data_provider.html',1,'OVRSkeleton']]],
  ['iovrskeletonrendererdataprovider_188',['IOVRSkeletonRendererDataProvider',['../interface_o_v_r_skeleton_renderer_1_1_i_o_v_r_skeleton_renderer_data_provider.html',1,'OVRSkeletonRenderer']]],
  ['iplatformvoiceservice_189',['IPlatformVoiceService',['../interface_oculus_1_1_voice_1_1_interfaces_1_1_i_platform_voice_service.html',1,'Oculus::Voice::Interfaces']]],
  ['ipointable_190',['IPointable',['../interface_oculus_1_1_interaction_1_1_i_pointable.html',1,'Oculus::Interaction']]],
  ['ipointablecanvas_191',['IPointableCanvas',['../interface_oculus_1_1_interaction_1_1_i_pointable_canvas.html',1,'Oculus::Interaction']]],
  ['ipointableelement_192',['IPointableElement',['../interface_oculus_1_1_interaction_1_1_i_pointable_element.html',1,'Oculus::Interaction']]],
  ['iposeinputdevice_193',['IPoseInputDevice',['../interface_oculus_1_1_interaction_1_1_throw_1_1_i_pose_input_device.html',1,'Oculus::Interaction::Throw']]],
  ['ireadonlyhandskeleton_194',['IReadOnlyHandSkeleton',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_read_only_hand_skeleton.html',1,'Oculus::Interaction::Input']]],
  ['ireadonlyhandskeletonjointlist_195',['IReadOnlyHandSkeletonJointList',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_read_only_hand_skeleton_joint_list.html',1,'Oculus::Interaction::Input']]],
  ['irelativetoref_196',['IRelativeToRef',['../interface_oculus_1_1_interaction_1_1_i_relative_to_ref.html',1,'Oculus::Interaction']]],
  ['iremotedrawable_197',['IRemoteDrawable',['../interface_oculus_1_1_interaction_1_1_editor_1_1_i_remote_drawable.html',1,'Oculus::Interaction::Editor']]],
  ['irequest_198',['IRequest',['../interface_meta_1_1_wit_ai_1_1_i_request.html',1,'Meta::WitAi']]],
  ['ireticledata_199',['IReticleData',['../interface_oculus_1_1_interaction_1_1_distance_reticles_1_1_i_reticle_data.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['irigidbodyref_200',['IRigidbodyRef',['../interface_oculus_1_1_interaction_1_1_i_rigidbody_ref.html',1,'Oculus::Interaction']]],
  ['isactive_201',['IsActive',['../class_meta_1_1_wit_ai_1_1_wit_request.html#a476abdaeecdfcce2aa724ed3e9e9814a',1,'Meta::WitAi::WitRequest']]],
  ['isadaptiveressupportedbyengine_202',['IsAdaptiveResSupportedByEngine',['../class_o_v_r_manager.html#abc78525c839c485f2e1815ee87bc7754',1,'OVRManager']]],
  ['iscachefull_203',['IsCacheFull',['../class_meta_1_1_wit_ai_1_1_t_t_s_1_1_integrations_1_1_t_t_s_runtime_cache.html#a5429604d517a892a3b95d66bdc55f8c8',1,'Meta::WitAi::TTS::Integrations::TTSRuntimeCache']]],
  ['iscomplete_204',['IsComplete',['../class_meta_1_1_wit_ai_1_1_requests_1_1_v_request.html#a825c1721606268b9fa4a5d3ce5cafbc5',1,'Meta::WitAi::Requests::VRequest']]],
  ['isconfigurationvalid_205',['IsConfigurationValid',['../class_meta_1_1_wit_ai_1_1_wit_service.html#a686e9e032edf370a38de4bbcf7ba9166',1,'Meta::WitAi::WitService']]],
  ['isdemoonly_206',['isDemoOnly',['../class_meta_1_1_wit_ai_1_1_data_1_1_configuration_1_1_wit_configuration.html#a91dfd30465fefa48cac6af621d07e841',1,'Meta::WitAi::Data::Configuration::WitConfiguration']]],
  ['isdynamic_207',['isDynamic',['../class_o_v_r_overlay.html#a6422c98db8d87604a5efcff9698e2ba8',1,'OVROverlay']]],
  ['iselector_208',['ISelector',['../interface_oculus_1_1_interaction_1_1_i_selector.html',1,'Oculus::Interaction']]],
  ['isenabled_209',['IsEnabled',['../class_oculus_1_1_platform_1_1_models_1_1_user_capability.html#ad744faedbe400965b49bcc1dc09baa53',1,'Oculus::Platform::Models::UserCapability']]],
  ['isenabled_210',['isEnabled',['../class_o_v_r_tracker.html#a4c6b574a6a7cd0296066f3f8bd8a205f',1,'OVRTracker']]],
  ['iserviceevents_211',['IServiceEvents',['../interface_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_i_service_events.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['isexternalsurface_212',['isExternalSurface',['../class_o_v_r_overlay.html#a4eb6c0455379a0d3b77705306f8046fa',1,'OVROverlay']]],
  ['isfocussed_213',['IsFocussed',['../class_o_v_r_raycaster.html#af717573305a0753aeaab69cf46f3a380',1,'OVRRaycaster']]],
  ['isgrabbed_214',['isGrabbed',['../class_o_v_r_grabbable.html#af293dc881ce57d3a666031122a8c30f8',1,'OVRGrabbable']]],
  ['ishandselectpalmfingerschanged_215',['IsHandSelectPalmFingersChanged',['../class_oculus_1_1_interaction_1_1_grab_a_p_i_1_1_hand_grab_a_p_i.html#af06453e88b27647235bcee5e1ebf4dfa',1,'Oculus::Interaction::GrabAPI::HandGrabAPI']]],
  ['ishandselectpinchfingerschanged_216',['IsHandSelectPinchFingersChanged',['../class_oculus_1_1_interaction_1_1_grab_a_p_i_1_1_hand_grab_a_p_i.html#a6fb4fb2e320ac99e4ba10091280f193d',1,'Oculus::Interaction::GrabAPI::HandGrabAPI']]],
  ['ishidden_217',['IsHidden',['../class_oculus_1_1_interaction_1_1_editor_1_1_editor_base.html#a7d7fa388e28e8ec785d1b763534e3be5',1,'Oculus::Interaction::Editor::EditorBase']]],
  ['ishighconfidence_218',['IsHighConfidence',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand.html#ac28b61180c52c0b776f26892fd870092',1,'Oculus.Interaction.Input.IHand.IsHighConfidence()'],['../class_oculus_1_1_interaction_1_1_input_1_1_hand_ref.html#a6bf6a658f851b6dbcd76b1822d2ad74e',1,'Oculus.Interaction.Input.HandRef.IsHighConfidence()'],['../class_oculus_1_1_interaction_1_1_input_1_1_hand.html#a8ab7d9a27e97d3485f1823af018c5ac1',1,'Oculus.Interaction.Input.Hand.IsHighConfidence()']]],
  ['ishmdpresent_219',['isHmdPresent',['../class_o_v_r_manager.html#a564db1fc6953e6a1eca79820cc57299d',1,'OVRManager']]],
  ['isinitialized_220',['IsInitialized',['../class_o_v_r_lip_sync.html#ae63511a03fbace2768a94a131a46d296',1,'OVRLipSync']]],
  ['isinputavailable_221',['IsInputAvailable',['../class_meta_1_1_wit_ai_1_1_lib_1_1_mic_base.html#aa786032d5028c5c73532754945ae1df0',1,'Meta.WitAi.Lib.MicBase.IsInputAvailable()'],['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_input_source.html#a96baa3e36ace8927cafc72e2e269c11e',1,'Meta.WitAi.Interfaces.IAudioInputSource.IsInputAvailable()'],['../class_meta_1_1_wit_ai_1_1_lib_1_1_mic.html#a08b1d3799989e7ed63f8b6bb43efeb5e',1,'Meta.WitAi.Lib.Mic.IsInputAvailable()']]],
  ['isinsection_222',['IsInSection',['../class_oculus_1_1_interaction_1_1_editor_1_1_editor_base.html#a84e564656ac67aadd70dd4dffc6ff273',1,'Oculus::Interaction::Editor::EditorBase']]],
  ['isinsightpassthroughenabled_223',['isInsightPassthroughEnabled',['../class_o_v_r_manager.html#a10fd7bd957490b396fcbd41f901917e0',1,'OVRManager']]],
  ['isinsightpassthroughinitialized_224',['IsInsightPassthroughInitialized',['../class_o_v_r_manager.html#af9d1d3cb45cdc2cd377514948b58035c',1,'OVRManager']]],
  ['isinsightpassthroughinitpending_225',['IsInsightPassthroughInitPending',['../class_o_v_r_manager.html#aca5aea7694ccfdebc20e1b7c93a83a47',1,'OVRManager']]],
  ['isinsightpassthroughsupported_226',['IsInsightPassthroughSupported',['../class_o_v_r_manager.html#a405f1d9a6f9203857080ddb565916ae7',1,'OVRManager']]],
  ['isjoinable_227',['IsJoinable',['../class_group_presence_sample.html#a89954c857de2c70f174766bb47ad0a32',1,'GroupPresenceSample']]],
  ['ismembershiplocked_228',['IsMembershipLocked',['../class_oculus_1_1_platform_1_1_models_1_1_room.html#a97ba9cc621f1775496951e4a266c407c',1,'Oculus::Platform::Models::Room']]],
  ['isnapposedelegate_229',['ISnapPoseDelegate',['../interface_oculus_1_1_interaction_1_1_i_snap_pose_delegate.html',1,'Oculus::Interaction']]],
  ['isperforming_230',['IsPerforming',['../class_meta_1_1_wit_ai_1_1_requests_1_1_v_request.html#a54163301d18e7d1ec4ea95ea9a903c8f',1,'Meta::WitAi::Requests::VRequest']]],
  ['ispointermoving_231',['IsPointerMoving',['../class_unity_engine_1_1_event_systems_1_1_o_v_r_input_module.html#a96b195af713535578aa7107a8e0a5527',1,'UnityEngine::EventSystems::OVRInputModule']]],
  ['ispointerposevalid_232',['IsPointerPoseValid',['../class_oculus_1_1_interaction_1_1_input_1_1_hand.html#a8a7f55f4f5334302c594f03702f29ddb',1,'Oculus.Interaction.Input.Hand.IsPointerPoseValid()'],['../class_oculus_1_1_interaction_1_1_input_1_1_hand_ref.html#a215cc8a7751432a49c0dad3dad727fac',1,'Oculus.Interaction.Input.HandRef.IsPointerPoseValid()'],['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand.html#a61e87da14034a04a1ce66ffa0669df3c',1,'Oculus.Interaction.Input.IHand.IsPointerPoseValid()']]],
  ['ispositiontracked_233',['isPositionTracked',['../class_o_v_r_tracker.html#a93a89e3ff9a017f5a9190ae8dbb0de53',1,'OVRTracker']]],
  ['ispostteleportrequested_234',['IsPostTeleportRequested',['../class_locomotion_teleport.html#a7cff094eb8fb13dd42726295c12f8155',1,'LocomotionTeleport']]],
  ['ispowersavingactive_235',['isPowerSavingActive',['../class_o_v_r_manager.html#a706e7758e2cd724a649b48ae43bb895f',1,'OVRManager']]],
  ['ispresent_236',['isPresent',['../class_o_v_r_tracker.html#a3bd37b63fe2751178cd8f807700ce714',1,'OVRTracker']]],
  ['ispreteleportrequested_237',['IsPreTeleportRequested',['../class_locomotion_teleport.html#aa5314131e346562c44d86c91e8499354',1,'LocomotionTeleport']]],
  ['isprivate_238',['isPrivate',['../struct_meta_1_1_wit_ai_1_1_data_1_1_info_1_1_wit_app_info.html#acfd88f7deaf2bf9e527afa0829920275',1,'Meta::WitAi::Data::Info::WitAppInfo']]],
  ['isprotectedcontent_239',['isProtectedContent',['../class_o_v_r_overlay.html#a1d52f454d07dddb73992d5b57d7154b5',1,'OVROverlay']]],
  ['isrecording_240',['IsRecording',['../class_meta_1_1_wit_ai_1_1_lib_1_1_mic.html#a174f599185339bfc857af359bfc5c05a',1,'Meta::WitAi::Lib::Mic']]],
  ['isrequestactive_241',['IsRequestActive',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_dictation_service.html#ad5a7c44566c75b3582a92eee4780d201',1,'Meta.WitAi.Dictation.DictationService.IsRequestActive()'],['../class_meta_1_1_wit_ai_1_1_voice_service.html#a2b057814f43151dce2f91037a934ba93',1,'Meta.WitAi.VoiceService.IsRequestActive()']]],
  ['isrunning_242',['IsRunning',['../class_meta_1_1_wit_ai_1_1_thread_utility_1_1_thread_performer.html#a0ba4411794e50d2331a6ed62e5ab8ae4',1,'Meta::WitAi::ThreadUtility::ThreadPerformer']]],
  ['issupportedplatform_243',['isSupportedPlatform',['../class_o_v_r_manager.html#a2cf90ec494e4cf6bc466b848f3887919',1,'OVRManager']]],
  ['issurfacegeometry_244',['IsSurfaceGeometry',['../class_o_v_r_passthrough_layer.html#a01a31cdef5033b3f216d1452017c630b',1,'OVRPassthroughLayer']]],
  ['istextvalid_245',['IsTextValid',['../class_meta_1_1_wit_ai_1_1_t_t_s_1_1_integrations_1_1_t_t_s_wit.html#a0c3f8d18d8bb498db0462b05a13b6c3e',1,'Meta.WitAi.TTS.Integrations.TTSWit.IsTextValid()'],['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_web_handler.html#a98dbc85176b27a736bd21ea0651b6b74',1,'Meta.WitAi.TTS.Interfaces.ITTSWebHandler.IsTextValid()']]],
  ['istracked_246',['IsTracked',['../class_o_v_r_scene_anchor.html#abe294f064af271eac91d7f417bbd16e9',1,'OVRSceneAnchor']]],
  ['istrackeddatavalid_247',['IsTrackedDataValid',['../class_oculus_1_1_interaction_1_1_input_1_1_hand_ref.html#a264c393cc1a4a6cb4679324cf750b8cf',1,'Oculus.Interaction.Input.HandRef.IsTrackedDataValid()'],['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand.html#a389df2699a4fa61a2b6613c1607d1e20',1,'Oculus.Interaction.Input.IHand.IsTrackedDataValid()'],['../class_oculus_1_1_interaction_1_1_input_1_1_hand.html#ac5fad71f6bd15bf62d6ca9601c5d7136',1,'Oculus.Interaction.Input.Hand.IsTrackedDataValid()']]],
  ['istransitioning_248',['IsTransitioning',['../class_locomotion_teleport.html#adedec57d048e8022bf60733b807fca64',1,'LocomotionTeleport']]],
  ['istriggering_249',['IsTriggering',['../struct_o_v_r_boundary_1_1_boundary_test_result.html#a0fe2ac9a8c1a69670e2ea0862fe6f9c9',1,'OVRBoundary::BoundaryTestResult']]],
  ['isurface_250',['ISurface',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['isurfacepatch_251',['ISurfacePatch',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_surface_patch.html',1,'Oculus::Interaction::Surfaces']]],
  ['isuserpresent_252',['isUserPresent',['../class_o_v_r_manager.html#a5e16257dc5068ef2fb2a1c383977025d',1,'OVRManager']]],
  ['isvaliddestination_253',['IsValidDestination',['../class_teleport_destination.html#a037e8866ed50f9f47ca3e6ba6489a45f',1,'TeleportDestination']]],
  ['iteleportarc_254',['ITeleportArc',['../interface_oculus_1_1_interaction_1_1_locomotion_1_1_i_teleport_arc.html',1,'Oculus::Interaction::Locomotion']]],
  ['itemrect_255',['ItemRect',['../class_o_v_r_1_1_audio_manager_inspector_1_1_item_rect.html',1,'OVR::AudioManagerInspector']]],
  ['itokenvalidationprovider_256',['ITokenValidationProvider',['../interface_meta_1_1_wit_ai_1_1_wit_auth_utility_1_1_i_token_validation_provider.html',1,'Meta::WitAi::WitAuthUtility']]],
  ['itrackingtoworldtransformer_257',['ITrackingToWorldTransformer',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_tracking_to_world_transformer.html',1,'Oculus::Interaction::Input']]],
  ['itranscriptionevent_258',['ITranscriptionEvent',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_event.html',1,'Meta::WitAi::Interfaces']]],
  ['itranscriptioneventprovider_259',['ITranscriptionEventProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_event_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['itranscriptionprovider_260',['ITranscriptionProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['itransformer_261',['ITransformer',['../interface_oculus_1_1_interaction_1_1_i_transformer.html',1,'Oculus::Interaction']]],
  ['itransformfeaturestateprovider_262',['ITransformFeatureStateProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_transform_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ittsdiskcachehandler_263',['ITTSDiskCacheHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_disk_cache_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittsruntimecachehandler_264',['ITTSRuntimeCacheHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_runtime_cache_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittsvoiceprovider_265',['ITTSVoiceProvider',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_voice_provider.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittswebhandler_266',['ITTSWebHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_web_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['iupdatedriver_267',['IUpdateDriver',['../interface_oculus_1_1_interaction_1_1_i_update_driver.html',1,'Oculus::Interaction']]],
  ['ivcbindingevents_268',['IVCBindingEvents',['../interface_oculus_1_1_voice_1_1_bindings_1_1_android_1_1_i_v_c_binding_events.html',1,'Oculus::Voice::Bindings::Android']]],
  ['ivelocitycalculator_269',['IVelocityCalculator',['../interface_oculus_1_1_interaction_1_1_throw_1_1_i_velocity_calculator.html',1,'Oculus::Interaction::Throw']]],
  ['ivoiceeventprovider_270',['IVoiceEventProvider',['../interface_meta_1_1_wit_ai_1_1_i_voice_event_provider.html',1,'Meta::WitAi']]],
  ['ivoicesdklogger_271',['IVoiceSDKLogger',['../interface_oculus_1_1_voice_1_1_core_1_1_bindings_1_1_interfaces_1_1_i_voice_s_d_k_logger.html',1,'Oculus::Voice::Core::Bindings::Interfaces']]],
  ['ivoiceservice_272',['IVoiceService',['../interface_meta_1_1_wit_ai_1_1_i_voice_service.html',1,'Meta::WitAi']]],
  ['ivoippcmsource_273',['IVoipPCMSource',['../interface_oculus_1_1_platform_1_1_i_voip_p_c_m_source.html',1,'Oculus::Platform']]],
  ['ivrapplications_274',['IVRApplications',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_applications.html',1,'OVR::OpenVR']]],
  ['ivrchaperone_275',['IVRChaperone',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_chaperone.html',1,'OVR::OpenVR']]],
  ['ivrchaperonesetup_276',['IVRChaperoneSetup',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_chaperone_setup.html',1,'OVR::OpenVR']]],
  ['ivrcompositor_277',['IVRCompositor',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_compositor.html',1,'OVR::OpenVR']]],
  ['ivrdrivermanager_278',['IVRDriverManager',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_driver_manager.html',1,'OVR::OpenVR']]],
  ['ivrextendeddisplay_279',['IVRExtendedDisplay',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_extended_display.html',1,'OVR::OpenVR']]],
  ['ivrinput_280',['IVRInput',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_input.html',1,'OVR::OpenVR']]],
  ['ivriobuffer_281',['IVRIOBuffer',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_i_o_buffer.html',1,'OVR::OpenVR']]],
  ['ivrnotifications_282',['IVRNotifications',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_notifications.html',1,'OVR::OpenVR']]],
  ['ivroverlay_283',['IVROverlay',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_overlay.html',1,'OVR::OpenVR']]],
  ['ivrrendermodels_284',['IVRRenderModels',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_render_models.html',1,'OVR::OpenVR']]],
  ['ivrresources_285',['IVRResources',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_resources.html',1,'OVR::OpenVR']]],
  ['ivrscreenshots_286',['IVRScreenshots',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_screenshots.html',1,'OVR::OpenVR']]],
  ['ivrsettings_287',['IVRSettings',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_settings.html',1,'OVR::OpenVR']]],
  ['ivrspatialanchors_288',['IVRSpatialAnchors',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_spatial_anchors.html',1,'OVR::OpenVR']]],
  ['ivrsystem_289',['IVRSystem',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_system.html',1,'OVR::OpenVR']]],
  ['ivrtrackedcamera_290',['IVRTrackedCamera',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_tracked_camera.html',1,'OVR::OpenVR']]],
  ['iwitbytedatareadyhandler_291',['IWitByteDataReadyHandler',['../interface_meta_1_1_wit_ai_1_1_events_1_1_i_wit_byte_data_ready_handler.html',1,'Meta::WitAi::Events']]],
  ['iwitbytedatasenthandler_292',['IWitByteDataSentHandler',['../interface_meta_1_1_wit_ai_1_1_events_1_1_i_wit_byte_data_sent_handler.html',1,'Meta::WitAi::Events']]],
  ['iwitrequestconfiguration_293',['IWitRequestConfiguration',['../interface_meta_1_1_wit_ai_1_1_i_wit_request_configuration.html',1,'Meta::WitAi']]],
  ['iwitrequestprovider_294',['IWitRequestProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_wit_request_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['iwitruntimeconfigprovider_295',['IWitRuntimeConfigProvider',['../interface_meta_1_1_wit_ai_1_1_i_wit_runtime_config_provider.html',1,'Meta::WitAi']]]
];
