var searchData=
[
  ['d3d12texturedata_5ft_0',['D3D12TextureData_t',['../struct_o_v_r_1_1_open_v_r_1_1_d3_d12_texture_data__t.html',1,'OVR::OpenVR']]],
  ['dataentry_1',['DataEntry',['../class_oculus_1_1_platform_1_1_samples_1_1_net_chat_1_1_data_entry.html',1,'Oculus.Platform.Samples.NetChat.DataEntry'],['../class_oculus_1_1_platform_1_1_samples_1_1_simple_platform_sample_1_1_data_entry.html',1,'Oculus.Platform.Samples.SimplePlatformSample.DataEntry']]],
  ['datamodifier_2',['DataModifier',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datamodifier_3c_20controllerdataasset_20_3e_3',['DataModifier&lt; ControllerDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datamodifier_3c_20handdataasset_20_3e_4',['DataModifier&lt; HandDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datamodifier_3c_20hmddataasset_20_3e_5',['DataModifier&lt; HmdDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datasource_6',['DataSource',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datasource_3c_20controllerdataasset_20_3e_7',['DataSource&lt; ControllerDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datasource_3c_20handdataasset_20_3e_8',['DataSource&lt; HandDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datasource_3c_20hmddataasset_20_3e_9',['DataSource&lt; HmdDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datetimeconverter_10',['DateTimeConverter',['../class_meta_1_1_wit_ai_1_1_json_1_1_date_time_converter.html',1,'Meta::WitAi::Json']]],
  ['datetimeutility_11',['DateTimeUtility',['../class_oculus_1_1_voice_1_1_core_1_1_utilities_1_1_date_time_utility.html',1,'Oculus::Voice::Core::Utilities']]],
  ['debuggizmos_12',['DebugGizmos',['../class_oculus_1_1_interaction_1_1_debug_gizmos.html',1,'Oculus::Interaction']]],
  ['debuguibuilder_13',['DebugUIBuilder',['../class_debug_u_i_builder.html',1,'']]],
  ['debuguisample_14',['DebugUISample',['../class_debug_u_i_sample.html',1,'']]],
  ['defaulttokenvalidatorprovider_15',['DefaultTokenValidatorProvider',['../class_meta_1_1_wit_ai_1_1_wit_auth_utility_1_1_default_token_validator_provider.html',1,'Meta::WitAi::WitAuthUtility']]],
  ['deferredpassthroughmeshaddition_16',['DeferredPassthroughMeshAddition',['../struct_o_v_r_passthrough_layer_1_1_deferred_passthrough_mesh_addition.html',1,'OVRPassthroughLayer']]],
  ['deserializablelist_17',['DeserializableList',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20achievementdefinition_20_3e_18',['DeserializableList&lt; AchievementDefinition &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20achievementprogress_20_3e_19',['DeserializableList&lt; AchievementProgress &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20applicationinvite_20_3e_20',['DeserializableList&lt; ApplicationInvite &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20assetdetails_20_3e_21',['DeserializableList&lt; AssetDetails &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20blockeduser_20_3e_22',['DeserializableList&lt; BlockedUser &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20calapplicationsuggestion_20_3e_23',['DeserializableList&lt; CalApplicationSuggestion &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20challenge_20_3e_24',['DeserializableList&lt; Challenge &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20challengeentry_20_3e_25',['DeserializableList&lt; ChallengeEntry &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20cloudstoragemetadata_20_3e_26',['DeserializableList&lt; CloudStorageMetadata &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20destination_20_3e_27',['DeserializableList&lt; Destination &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20installedapplication_20_3e_28',['DeserializableList&lt; InstalledApplication &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20leaderboard_20_3e_29',['DeserializableList&lt; Leaderboard &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20leaderboardentry_20_3e_30',['DeserializableList&lt; LeaderboardEntry &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20linkedaccount_20_3e_31',['DeserializableList&lt; LinkedAccount &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20matchmakingadminsnapshotcandidate_20_3e_32',['DeserializableList&lt; MatchmakingAdminSnapshotCandidate &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20matchmakingenqueueduser_20_3e_33',['DeserializableList&lt; MatchmakingEnqueuedUser &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20netsyncsession_20_3e_34',['DeserializableList&lt; NetSyncSession &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20netsyncvoipattenuationvalue_20_3e_35',['DeserializableList&lt; NetSyncVoipAttenuationValue &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20pid_20_3e_36',['DeserializableList&lt; Pid &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20product_20_3e_37',['DeserializableList&lt; Product &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20purchase_20_3e_38',['DeserializableList&lt; Purchase &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20room_20_3e_39',['DeserializableList&lt; Room &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20roominvitenotification_20_3e_40',['DeserializableList&lt; RoomInviteNotification &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20sdkaccount_20_3e_41',['DeserializableList&lt; SdkAccount &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20team_20_3e_42',['DeserializableList&lt; Team &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20user_20_3e_43',['DeserializableList&lt; User &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20userandroom_20_3e_44',['DeserializableList&lt; UserAndRoom &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20usercapability_20_3e_45',['DeserializableList&lt; UserCapability &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['destination_46',['Destination',['../class_oculus_1_1_platform_1_1_models_1_1_destination.html',1,'Oculus::Platform::Models']]],
  ['destinationlist_47',['DestinationList',['../class_oculus_1_1_platform_1_1_models_1_1_destination_list.html',1,'Oculus::Platform::Models']]],
  ['detectbasket_48',['DetectBasket',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_detect_basket.html',1,'Oculus::Platform::Samples::VrHoops']]],
  ['dictationconfiguration_49',['DictationConfiguration',['../class_oculus_1_1_voice_1_1_dictation_1_1_configuration_1_1_dictation_configuration.html',1,'Oculus::Voice::Dictation::Configuration']]],
  ['dictationconfigurationbinding_50',['DictationConfigurationBinding',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_dictation_configuration_binding.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['dictationeventpropertydrawer_51',['DictationEventPropertyDrawer',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_events_1_1_editor_1_1_dictation_event_property_drawer.html',1,'Meta::WitAi::Dictation::Events::Editor']]],
  ['dictationevents_52',['DictationEvents',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_events_1_1_dictation_events.html',1,'Meta::WitAi::Dictation::Events']]],
  ['dictationlistener_53',['DictationListener',['../interface_oculus_1_1_voice_1_1_dictation_1_1_listeners_1_1_dictation_listener.html',1,'Oculus::Voice::Dictation::Listeners']]],
  ['dictationlistenerbinding_54',['DictationListenerBinding',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_dictation_listener_binding.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['dictationservice_55',['DictationService',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_dictation_service.html',1,'Meta::WitAi::Dictation']]],
  ['dictationserviceaudioeventreference_56',['DictationServiceAudioEventReference',['../class_meta_1_1_wit_ai_1_1_service_references_1_1_dictation_service_audio_event_reference.html',1,'Meta::WitAi::ServiceReferences']]],
  ['dictationservicereference_57',['DictationServiceReference',['../struct_meta_1_1_wit_ai_1_1_utilities_1_1_dictation_service_reference.html',1,'Meta::WitAi::Utilities']]],
  ['dictationsession_58',['DictationSession',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_data_1_1_dictation_session.html',1,'Meta::WitAi::Dictation::Data']]],
  ['dictationsessionevent_59',['DictationSessionEvent',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_events_1_1_dictation_session_event.html',1,'Meta::WitAi::Dictation::Events']]],
  ['dictionarylist_60',['DictionaryList',['../class_meta_1_1_wit_ai_1_1_utilities_1_1_dictionary_list.html',1,'Meta::WitAi::Utilities']]],
  ['displayrefreshratechangeddata_61',['DisplayRefreshRateChangedData',['../struct_o_v_r_deserialize_1_1_display_refresh_rate_changed_data.html',1,'OVRDeserialize']]],
  ['distancegrabbable_62',['DistanceGrabbable',['../class_oculus_sample_framework_1_1_distance_grabbable.html',1,'OculusSampleFramework']]],
  ['distancegrabber_63',['DistanceGrabber',['../class_oculus_sample_framework_1_1_distance_grabber.html',1,'OculusSampleFramework']]],
  ['distancegrabbersample_64',['DistanceGrabberSample',['../class_oculus_sample_framework_1_1_distance_grabber_sample.html',1,'OculusSampleFramework']]],
  ['distancegrabinteractable_65',['DistanceGrabInteractable',['../class_oculus_1_1_interaction_1_1_distance_grab_interactable.html',1,'Oculus::Interaction']]],
  ['distancegrabinteractor_66',['DistanceGrabInteractor',['../class_oculus_1_1_interaction_1_1_distance_grab_interactor.html',1,'Oculus::Interaction']]],
  ['distancehandgrabinteractable_67',['DistanceHandGrabInteractable',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_distance_hand_grab_interactable.html',1,'Oculus::Interaction::HandGrab']]],
  ['distancehandgrabinteractor_68',['DistanceHandGrabInteractor',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_distance_hand_grab_interactor.html',1,'Oculus::Interaction::HandGrab']]],
  ['distantcandidatecomputer_69',['DistantCandidateComputer',['../class_oculus_1_1_interaction_1_1_distant_candidate_computer.html',1,'Oculus::Interaction']]],
  ['distantcandidatecomputer_3c_20oculus_3a_3ainteraction_3a_3adistancegrabinteractor_2c_20oculus_3a_3ainteraction_3a_3adistancegrabinteractable_20_3e_70',['DistantCandidateComputer&lt; Oculus::Interaction::DistanceGrabInteractor, Oculus::Interaction::DistanceGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_distant_candidate_computer.html',1,'Oculus::Interaction']]],
  ['distantcandidatecomputer_3c_20oculus_3a_3ainteraction_3a_3ahandgrab_3a_3adistancehandgrabinteractor_2c_20oculus_3a_3ainteraction_3a_3ahandgrab_3a_3adistancehandgrabinteractable_20_3e_71',['DistantCandidateComputer&lt; Oculus::Interaction::HandGrab::DistanceHandGrabInteractor, Oculus::Interaction::HandGrab::DistanceHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_distant_candidate_computer.html',1,'Oculus::Interaction']]],
  ['distantinteractionlinerenderervisual_72',['DistantInteractionLineRendererVisual',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_line_renderer_visual.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['distantinteractionlinevisual_73',['DistantInteractionLineVisual',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_line_visual.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['distantinteractionpolylinevisual_74',['DistantInteractionPolylineVisual',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_polyline_visual.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['distantinteractiontubevisual_75',['DistantInteractionTubeVisual',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_tube_visual.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['distantpointdetector_76',['DistantPointDetector',['../class_oculus_1_1_interaction_1_1_distant_point_detector.html',1,'Oculus::Interaction']]],
  ['distantpointdetectorfrustums_77',['DistantPointDetectorFrustums',['../struct_oculus_1_1_interaction_1_1_distant_point_detector_frustums.html',1,'Oculus::Interaction']]],
  ['distortioncoordinates_5ft_78',['DistortionCoordinates_t',['../struct_o_v_r_1_1_open_v_r_1_1_distortion_coordinates__t.html',1,'OVR::OpenVR']]],
  ['dotgridproperties_79',['DotGridProperties',['../class_oculus_1_1_interaction_1_1_dot_grid_properties.html',1,'Oculus::Interaction']]],
  ['dragthresholdsconfig_80',['DragThresholdsConfig',['../class_oculus_1_1_interaction_1_1_poke_interactable_1_1_drag_thresholds_config.html',1,'Oculus::Interaction::PokeInteractable']]],
  ['drawerinspectorcomment_81',['DrawerInspectorComment',['../class_drawer_inspector_comment.html',1,'']]],
  ['drawerinspectornote_82',['DrawerInspectorNote',['../class_drawer_inspector_note.html',1,'']]],
  ['driverdirectmode_5fframetiming_83',['DriverDirectMode_FrameTiming',['../struct_o_v_r_1_1_open_v_r_1_1_driver_direct_mode___frame_timing.html',1,'OVR::OpenVR']]],
  ['dropdownsample_84',['DropdownSample',['../class_dropdown_sample.html',1,'']]],
  ['dummypointreticle_85',['DummyPointReticle',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_line_visual_1_1_dummy_point_reticle.html',1,'Oculus::Interaction::DistanceReticles::DistantInteractionLineVisual']]],
  ['dynamicentitydataprovider_86',['DynamicEntityDataProvider',['../class_meta_1_1_wit_ai_1_1_data_1_1_entities_1_1_dynamic_entity_data_provider.html',1,'Meta::WitAi::Data::Entities']]],
  ['dynamicentitykeywordregistry_87',['DynamicEntityKeywordRegistry',['../class_meta_1_1_wit_ai_1_1_data_1_1_entities_1_1_dynamic_entity_keyword_registry.html',1,'Meta::WitAi::Data::Entities']]],
  ['dynamicentityprovider_88',['DynamicEntityProvider',['../class_meta_1_1_wit_ai_1_1_data_1_1_entities_1_1_dynamic_entity_provider.html',1,'Meta::WitAi::Data::Entities']]],
  ['dynamicmoveprovider_89',['DynamicMoveProvider',['../class_unity_engine_1_1_x_r_1_1_interaction_1_1_toolkit_1_1_samples_1_1_starter_assets_1_1_dynamic_move_provider.html',1,'UnityEngine::XR::Interaction::Toolkit::Samples::StarterAssets']]],
  ['dynamicrangeattribute_90',['DynamicRangeAttribute',['../class_meta_1_1_wit_ai_1_1_utilities_1_1_dynamic_range_attribute.html',1,'Meta::WitAi::Utilities']]],
  ['dynamicrangeattributedrawer_91',['DynamicRangeAttributeDrawer',['../class_meta_1_1_wit_ai_1_1_drawers_1_1_dynamic_range_attribute_drawer.html',1,'Meta::WitAi::Drawers']]]
];
