var searchData=
[
  ['maction_0',['MAction',['../interface_oculus_1_1_interaction_1_1_m_action.html',1,'Oculus::Interaction']]],
  ['maction_3c_20t_20_3e_1',['MAction&lt; T &gt;',['../interface_oculus_1_1_interaction_1_1_m_action.html',1,'Oculus::Interaction']]],
  ['manifestloader_2',['ManifestLoader',['../class_meta_1_1_conduit_1_1_manifest_loader.html',1,'Meta::Conduit']]],
  ['marker_3',['Marker',['../class_meta_1_1_wit_ai_1_1_data_1_1_ring_buffer_1_1_marker.html',1,'Meta::WitAi::Data::RingBuffer']]],
  ['matchcontroller_4',['MatchController',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_match_controller.html',1,'Oculus::Platform::Samples::VrHoops']]],
  ['matchintent_5',['MatchIntent',['../class_meta_1_1_wit_ai_1_1_match_intent.html',1,'Meta::WitAi']]],
  ['matchmakingadminsnapshot_6',['MatchmakingAdminSnapshot',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_admin_snapshot.html',1,'Oculus::Platform::Models']]],
  ['matchmakingadminsnapshotcandidate_7',['MatchmakingAdminSnapshotCandidate',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_admin_snapshot_candidate.html',1,'Oculus::Platform::Models']]],
  ['matchmakingadminsnapshotcandidatelist_8',['MatchmakingAdminSnapshotCandidateList',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_admin_snapshot_candidate_list.html',1,'Oculus::Platform::Models']]],
  ['matchmakingbrowseresult_9',['MatchmakingBrowseResult',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_browse_result.html',1,'Oculus::Platform::Models']]],
  ['matchmakingenqueueduser_10',['MatchmakingEnqueuedUser',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_enqueued_user.html',1,'Oculus::Platform::Models']]],
  ['matchmakingenqueueduserlist_11',['MatchmakingEnqueuedUserList',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_enqueued_user_list.html',1,'Oculus::Platform::Models']]],
  ['matchmakingenqueueresult_12',['MatchmakingEnqueueResult',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_enqueue_result.html',1,'Oculus::Platform::Models']]],
  ['matchmakingenqueueresultandroom_13',['MatchmakingEnqueueResultAndRoom',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_enqueue_result_and_room.html',1,'Oculus::Platform::Models']]],
  ['matchmakingmanager_14',['MatchmakingManager',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_board_game_1_1_matchmaking_manager.html',1,'Oculus.Platform.Samples.VrBoardGame.MatchmakingManager'],['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_matchmaking_manager.html',1,'Oculus.Platform.Samples.VrHoops.MatchmakingManager']]],
  ['matchmakingoptions_15',['MatchmakingOptions',['../class_oculus_1_1_platform_1_1_matchmaking_options.html',1,'Oculus::Platform']]],
  ['matchmakingstats_16',['MatchmakingStats',['../class_oculus_1_1_platform_1_1_models_1_1_matchmaking_stats.html',1,'Oculus::Platform::Models']]],
  ['materialpropertyblockeditor_17',['MaterialPropertyBlockEditor',['../class_oculus_1_1_interaction_1_1_material_property_block_editor.html',1,'Oculus::Interaction']]],
  ['materialpropertycolor_18',['MaterialPropertyColor',['../struct_oculus_1_1_interaction_1_1_material_property_color.html',1,'Oculus::Interaction']]],
  ['materialpropertyfloat_19',['MaterialPropertyFloat',['../struct_oculus_1_1_interaction_1_1_material_property_float.html',1,'Oculus::Interaction']]],
  ['materialpropertyvector_20',['MaterialPropertyVector',['../struct_oculus_1_1_interaction_1_1_material_property_vector.html',1,'Oculus::Interaction']]],
  ['media_21',['Media',['../class_o_v_r_plugin_1_1_media.html',1,'OVRPlugin']]],
  ['mediaplayerimage_22',['MediaPlayerImage',['../class_media_player_image.html',1,'']]],
  ['mediaplayerimageeditor_23',['MediaPlayerImageEditor',['../class_media_player_image_editor.html',1,'']]],
  ['mesh_24',['Mesh',['../class_o_v_r_plugin_1_1_mesh.html',1,'OVRPlugin']]],
  ['meshblit_25',['MeshBlit',['../class_oculus_1_1_interaction_1_1_demo_1_1_mesh_blit.html',1,'Oculus::Interaction::Demo']]],
  ['meshgenerationsettings_26',['MeshGenerationSettings',['../struct_oculus_1_1_interaction_1_1_unity_canvas_1_1_canvas_cylinder_1_1_mesh_generation_settings.html',1,'Oculus::Interaction::UnityCanvas::CanvasCylinder']]],
  ['meshgroup_27',['MeshGroup',['../struct_oculus_1_1_spatializer_1_1_propagation_1_1_mesh_group.html',1,'Oculus::Spatializer::Propagation']]],
  ['meshmaterial_28',['MeshMaterial',['../struct_o_n_s_p_propagation_geometry_1_1_mesh_material.html',1,'ONSPPropagationGeometry']]],
  ['meshrendererdata_29',['MeshRendererData',['../struct_o_v_r_mesh_renderer_1_1_mesh_renderer_data.html',1,'OVRMeshRenderer']]],
  ['message_30',['Message',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20abusereportrecording_20_3e_31',['Message&lt; AbuseReportRecording &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20achievementdefinitionlist_20_3e_32',['Message&lt; AchievementDefinitionList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20achievementprogresslist_20_3e_33',['Message&lt; AchievementProgressList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20achievementupdate_20_3e_34',['Message&lt; AchievementUpdate &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20applicationinvitelist_20_3e_35',['Message&lt; ApplicationInviteList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20applicationversion_20_3e_36',['Message&lt; ApplicationVersion &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20assetdetails_20_3e_37',['Message&lt; AssetDetails &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20assetdetailslist_20_3e_38',['Message&lt; AssetDetailsList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20assetfiledeleteresult_20_3e_39',['Message&lt; AssetFileDeleteResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20assetfiledownloadcancelresult_20_3e_40',['Message&lt; AssetFileDownloadCancelResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20assetfiledownloadresult_20_3e_41',['Message&lt; AssetFileDownloadResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20assetfiledownloadupdate_20_3e_42',['Message&lt; AssetFileDownloadUpdate &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20avatareditorresult_20_3e_43',['Message&lt; AvatarEditorResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20blockeduserlist_20_3e_44',['Message&lt; BlockedUserList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20bool_20_3e_45',['Message&lt; bool &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20calapplicationfinalized_20_3e_46',['Message&lt; CalApplicationFinalized &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20calapplicationproposed_20_3e_47',['Message&lt; CalApplicationProposed &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20calapplicationsuggestionlist_20_3e_48',['Message&lt; CalApplicationSuggestionList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20challenge_20_3e_49',['Message&lt; Challenge &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20challengeentrylist_20_3e_50',['Message&lt; ChallengeEntryList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20challengelist_20_3e_51',['Message&lt; ChallengeList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20cloudstorageconflictmetadata_20_3e_52',['Message&lt; CloudStorageConflictMetadata &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20cloudstoragedata_20_3e_53',['Message&lt; CloudStorageData &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20cloudstoragemetadata_20_3e_54',['Message&lt; CloudStorageMetadata &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20cloudstoragemetadatalist_20_3e_55',['Message&lt; CloudStorageMetadataList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20cloudstorageupdateresponse_20_3e_56',['Message&lt; CloudStorageUpdateResponse &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20destinationlist_20_3e_57',['Message&lt; DestinationList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20dictionary_3c_20string_2c_20string_20_3e_20_3e_58',['Message&lt; Dictionary&lt; string, string &gt; &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20grouppresencejoinintent_20_3e_59',['Message&lt; GroupPresenceJoinIntent &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20grouppresenceleaveintent_20_3e_60',['Message&lt; GroupPresenceLeaveIntent &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20httptransferupdate_20_3e_61',['Message&lt; HttpTransferUpdate &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20installedapplicationlist_20_3e_62',['Message&lt; InstalledApplicationList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20invitepanelresultinfo_20_3e_63',['Message&lt; InvitePanelResultInfo &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20launchblockflowresult_20_3e_64',['Message&lt; LaunchBlockFlowResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20launchfriendrequestflowresult_20_3e_65',['Message&lt; LaunchFriendRequestFlowResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20launchinvitepanelflowresult_20_3e_66',['Message&lt; LaunchInvitePanelFlowResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20launchreportflowresult_20_3e_67',['Message&lt; LaunchReportFlowResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20launchunblockflowresult_20_3e_68',['Message&lt; LaunchUnblockFlowResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20leaderboardentrylist_20_3e_69',['Message&lt; LeaderboardEntryList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20leaderboardlist_20_3e_70',['Message&lt; LeaderboardList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20linkedaccountlist_20_3e_71',['Message&lt; LinkedAccountList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20livestreamingapplicationstatus_20_3e_72',['Message&lt; LivestreamingApplicationStatus &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20livestreamingstartresult_20_3e_73',['Message&lt; LivestreamingStartResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20livestreamingstatus_20_3e_74',['Message&lt; LivestreamingStatus &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20livestreamingvideostats_20_3e_75',['Message&lt; LivestreamingVideoStats &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20matchmakingadminsnapshot_20_3e_76',['Message&lt; MatchmakingAdminSnapshot &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20matchmakingbrowseresult_20_3e_77',['Message&lt; MatchmakingBrowseResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20matchmakingenqueueresult_20_3e_78',['Message&lt; MatchmakingEnqueueResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20matchmakingenqueueresultandroom_20_3e_79',['Message&lt; MatchmakingEnqueueResultAndRoom &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20matchmakingstats_20_3e_80',['Message&lt; MatchmakingStats &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20microphoneavailabilitystate_20_3e_81',['Message&lt; MicrophoneAvailabilityState &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20netsyncconnection_20_3e_82',['Message&lt; NetSyncConnection &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20netsyncsessionlist_20_3e_83',['Message&lt; NetSyncSessionList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20netsyncsessionschangednotification_20_3e_84',['Message&lt; NetSyncSessionsChangedNotification &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20netsyncsetsessionpropertyresult_20_3e_85',['Message&lt; NetSyncSetSessionPropertyResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20netsyncvoipattenuationvaluelist_20_3e_86',['Message&lt; NetSyncVoipAttenuationValueList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20networkingpeer_20_3e_87',['Message&lt; NetworkingPeer &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20orgscopedid_20_3e_88',['Message&lt; OrgScopedID &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20party_20_3e_89',['Message&lt; Party &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20partyid_20_3e_90',['Message&lt; PartyID &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20partyupdatenotification_20_3e_91',['Message&lt; PartyUpdateNotification &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20pidlist_20_3e_92',['Message&lt; PidList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20pingresult_20_3e_93',['Message&lt; PingResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20platforminitialize_20_3e_94',['Message&lt; PlatformInitialize &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20productlist_20_3e_95',['Message&lt; ProductList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20purchase_20_3e_96',['Message&lt; Purchase &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20purchaselist_20_3e_97',['Message&lt; PurchaseList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20rejoindialogresult_20_3e_98',['Message&lt; RejoinDialogResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20room_20_3e_99',['Message&lt; Room &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20roominvitenotification_20_3e_100',['Message&lt; RoomInviteNotification &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20roominvitenotificationlist_20_3e_101',['Message&lt; RoomInviteNotificationList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20roomlist_20_3e_102',['Message&lt; RoomList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20sdkaccountlist_20_3e_103',['Message&lt; SdkAccountList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20sendinvitesresult_20_3e_104',['Message&lt; SendInvitesResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20sharemediaresult_20_3e_105',['Message&lt; ShareMediaResult &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20string_20_3e_106',['Message&lt; string &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20systemvoipstate_20_3e_107',['Message&lt; SystemVoipState &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20user_20_3e_108',['Message&lt; User &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20userandroomlist_20_3e_109',['Message&lt; UserAndRoomList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20usercapabilitylist_20_3e_110',['Message&lt; UserCapabilityList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20userdatastoreupdateresponse_20_3e_111',['Message&lt; UserDataStoreUpdateResponse &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20userlist_20_3e_112',['Message&lt; UserList &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20userproof_20_3e_113',['Message&lt; UserProof &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['message_3c_20userreportid_20_3e_114',['Message&lt; UserReportID &gt;',['../class_oculus_1_1_platform_1_1_message.html',1,'Oculus::Platform']]],
  ['messagewithabusereportrecording_115',['MessageWithAbuseReportRecording',['../class_oculus_1_1_platform_1_1_message_with_abuse_report_recording.html',1,'Oculus::Platform']]],
  ['messagewithachievementdefinitions_116',['MessageWithAchievementDefinitions',['../class_oculus_1_1_platform_1_1_message_with_achievement_definitions.html',1,'Oculus::Platform']]],
  ['messagewithachievementprogresslist_117',['MessageWithAchievementProgressList',['../class_oculus_1_1_platform_1_1_message_with_achievement_progress_list.html',1,'Oculus::Platform']]],
  ['messagewithachievementupdate_118',['MessageWithAchievementUpdate',['../class_oculus_1_1_platform_1_1_message_with_achievement_update.html',1,'Oculus::Platform']]],
  ['messagewithapplicationinvitelist_119',['MessageWithApplicationInviteList',['../class_oculus_1_1_platform_1_1_message_with_application_invite_list.html',1,'Oculus::Platform']]],
  ['messagewithapplicationversion_120',['MessageWithApplicationVersion',['../class_oculus_1_1_platform_1_1_message_with_application_version.html',1,'Oculus::Platform']]],
  ['messagewithassetdetails_121',['MessageWithAssetDetails',['../class_oculus_1_1_platform_1_1_message_with_asset_details.html',1,'Oculus::Platform']]],
  ['messagewithassetdetailslist_122',['MessageWithAssetDetailsList',['../class_oculus_1_1_platform_1_1_message_with_asset_details_list.html',1,'Oculus::Platform']]],
  ['messagewithassetfiledeleteresult_123',['MessageWithAssetFileDeleteResult',['../class_oculus_1_1_platform_1_1_message_with_asset_file_delete_result.html',1,'Oculus::Platform']]],
  ['messagewithassetfiledownloadcancelresult_124',['MessageWithAssetFileDownloadCancelResult',['../class_oculus_1_1_platform_1_1_message_with_asset_file_download_cancel_result.html',1,'Oculus::Platform']]],
  ['messagewithassetfiledownloadresult_125',['MessageWithAssetFileDownloadResult',['../class_oculus_1_1_platform_1_1_message_with_asset_file_download_result.html',1,'Oculus::Platform']]],
  ['messagewithassetfiledownloadupdate_126',['MessageWithAssetFileDownloadUpdate',['../class_oculus_1_1_platform_1_1_message_with_asset_file_download_update.html',1,'Oculus::Platform']]],
  ['messagewithavatareditorresult_127',['MessageWithAvatarEditorResult',['../class_oculus_1_1_platform_1_1_message_with_avatar_editor_result.html',1,'Oculus::Platform']]],
  ['messagewithblockeduserlist_128',['MessageWithBlockedUserList',['../class_oculus_1_1_platform_1_1_message_with_blocked_user_list.html',1,'Oculus::Platform']]],
  ['messagewithcalapplicationfinalized_129',['MessageWithCalApplicationFinalized',['../class_oculus_1_1_platform_1_1_message_with_cal_application_finalized.html',1,'Oculus::Platform']]],
  ['messagewithcalapplicationproposed_130',['MessageWithCalApplicationProposed',['../class_oculus_1_1_platform_1_1_message_with_cal_application_proposed.html',1,'Oculus::Platform']]],
  ['messagewithcalapplicationsuggestionlist_131',['MessageWithCalApplicationSuggestionList',['../class_oculus_1_1_platform_1_1_message_with_cal_application_suggestion_list.html',1,'Oculus::Platform']]],
  ['messagewithchallenge_132',['MessageWithChallenge',['../class_oculus_1_1_platform_1_1_message_with_challenge.html',1,'Oculus::Platform']]],
  ['messagewithchallengeentrylist_133',['MessageWithChallengeEntryList',['../class_oculus_1_1_platform_1_1_message_with_challenge_entry_list.html',1,'Oculus::Platform']]],
  ['messagewithchallengelist_134',['MessageWithChallengeList',['../class_oculus_1_1_platform_1_1_message_with_challenge_list.html',1,'Oculus::Platform']]],
  ['messagewithcloudstorageconflictmetadata_135',['MessageWithCloudStorageConflictMetadata',['../class_oculus_1_1_platform_1_1_message_with_cloud_storage_conflict_metadata.html',1,'Oculus::Platform']]],
  ['messagewithcloudstoragedata_136',['MessageWithCloudStorageData',['../class_oculus_1_1_platform_1_1_message_with_cloud_storage_data.html',1,'Oculus::Platform']]],
  ['messagewithcloudstoragemetadatalist_137',['MessageWithCloudStorageMetadataList',['../class_oculus_1_1_platform_1_1_message_with_cloud_storage_metadata_list.html',1,'Oculus::Platform']]],
  ['messagewithcloudstoragemetadataunderlocal_138',['MessageWithCloudStorageMetadataUnderLocal',['../class_oculus_1_1_platform_1_1_message_with_cloud_storage_metadata_under_local.html',1,'Oculus::Platform']]],
  ['messagewithcloudstorageupdateresponse_139',['MessageWithCloudStorageUpdateResponse',['../class_oculus_1_1_platform_1_1_message_with_cloud_storage_update_response.html',1,'Oculus::Platform']]],
  ['messagewithdatastoreunderprivateuserdatastore_140',['MessageWithDataStoreUnderPrivateUserDataStore',['../class_oculus_1_1_platform_1_1_message_with_data_store_under_private_user_data_store.html',1,'Oculus::Platform']]],
  ['messagewithdatastoreunderpublicuserdatastore_141',['MessageWithDataStoreUnderPublicUserDataStore',['../class_oculus_1_1_platform_1_1_message_with_data_store_under_public_user_data_store.html',1,'Oculus::Platform']]],
  ['messagewithdestinationlist_142',['MessageWithDestinationList',['../class_oculus_1_1_platform_1_1_message_with_destination_list.html',1,'Oculus::Platform']]],
  ['messagewithgrouppresencejoinintent_143',['MessageWithGroupPresenceJoinIntent',['../class_oculus_1_1_platform_1_1_message_with_group_presence_join_intent.html',1,'Oculus::Platform']]],
  ['messagewithgrouppresenceleaveintent_144',['MessageWithGroupPresenceLeaveIntent',['../class_oculus_1_1_platform_1_1_message_with_group_presence_leave_intent.html',1,'Oculus::Platform']]],
  ['messagewithhttptransferupdate_145',['MessageWithHttpTransferUpdate',['../class_oculus_1_1_platform_1_1_message_with_http_transfer_update.html',1,'Oculus::Platform']]],
  ['messagewithinstalledapplicationlist_146',['MessageWithInstalledApplicationList',['../class_oculus_1_1_platform_1_1_message_with_installed_application_list.html',1,'Oculus::Platform']]],
  ['messagewithinvitepanelresultinfo_147',['MessageWithInvitePanelResultInfo',['../class_oculus_1_1_platform_1_1_message_with_invite_panel_result_info.html',1,'Oculus::Platform']]],
  ['messagewithlaunchblockflowresult_148',['MessageWithLaunchBlockFlowResult',['../class_oculus_1_1_platform_1_1_message_with_launch_block_flow_result.html',1,'Oculus::Platform']]],
  ['messagewithlaunchfriendrequestflowresult_149',['MessageWithLaunchFriendRequestFlowResult',['../class_oculus_1_1_platform_1_1_message_with_launch_friend_request_flow_result.html',1,'Oculus::Platform']]],
  ['messagewithlaunchinvitepanelflowresult_150',['MessageWithLaunchInvitePanelFlowResult',['../class_oculus_1_1_platform_1_1_message_with_launch_invite_panel_flow_result.html',1,'Oculus::Platform']]],
  ['messagewithlaunchreportflowresult_151',['MessageWithLaunchReportFlowResult',['../class_oculus_1_1_platform_1_1_message_with_launch_report_flow_result.html',1,'Oculus::Platform']]],
  ['messagewithlaunchunblockflowresult_152',['MessageWithLaunchUnblockFlowResult',['../class_oculus_1_1_platform_1_1_message_with_launch_unblock_flow_result.html',1,'Oculus::Platform']]],
  ['messagewithleaderboarddidupdate_153',['MessageWithLeaderboardDidUpdate',['../class_oculus_1_1_platform_1_1_message_with_leaderboard_did_update.html',1,'Oculus::Platform']]],
  ['messagewithleaderboardentrylist_154',['MessageWithLeaderboardEntryList',['../class_oculus_1_1_platform_1_1_message_with_leaderboard_entry_list.html',1,'Oculus::Platform']]],
  ['messagewithleaderboardlist_155',['MessageWithLeaderboardList',['../class_oculus_1_1_platform_1_1_message_with_leaderboard_list.html',1,'Oculus::Platform']]],
  ['messagewithlinkedaccountlist_156',['MessageWithLinkedAccountList',['../class_oculus_1_1_platform_1_1_message_with_linked_account_list.html',1,'Oculus::Platform']]],
  ['messagewithlivestreamingapplicationstatus_157',['MessageWithLivestreamingApplicationStatus',['../class_oculus_1_1_platform_1_1_message_with_livestreaming_application_status.html',1,'Oculus::Platform']]],
  ['messagewithlivestreamingstartresult_158',['MessageWithLivestreamingStartResult',['../class_oculus_1_1_platform_1_1_message_with_livestreaming_start_result.html',1,'Oculus::Platform']]],
  ['messagewithlivestreamingstatus_159',['MessageWithLivestreamingStatus',['../class_oculus_1_1_platform_1_1_message_with_livestreaming_status.html',1,'Oculus::Platform']]],
  ['messagewithlivestreamingvideostats_160',['MessageWithLivestreamingVideoStats',['../class_oculus_1_1_platform_1_1_message_with_livestreaming_video_stats.html',1,'Oculus::Platform']]],
  ['messagewithmatchmakingadminsnapshot_161',['MessageWithMatchmakingAdminSnapshot',['../class_oculus_1_1_platform_1_1_message_with_matchmaking_admin_snapshot.html',1,'Oculus::Platform']]],
  ['messagewithmatchmakingbrowseresult_162',['MessageWithMatchmakingBrowseResult',['../class_oculus_1_1_platform_1_1_message_with_matchmaking_browse_result.html',1,'Oculus::Platform']]],
  ['messagewithmatchmakingenqueueresult_163',['MessageWithMatchmakingEnqueueResult',['../class_oculus_1_1_platform_1_1_message_with_matchmaking_enqueue_result.html',1,'Oculus::Platform']]],
  ['messagewithmatchmakingenqueueresultandroom_164',['MessageWithMatchmakingEnqueueResultAndRoom',['../class_oculus_1_1_platform_1_1_message_with_matchmaking_enqueue_result_and_room.html',1,'Oculus::Platform']]],
  ['messagewithmatchmakingnotification_165',['MessageWithMatchmakingNotification',['../class_oculus_1_1_platform_1_1_message_with_matchmaking_notification.html',1,'Oculus::Platform']]],
  ['messagewithmatchmakingstatsundermatchmakingstats_166',['MessageWithMatchmakingStatsUnderMatchmakingStats',['../class_oculus_1_1_platform_1_1_message_with_matchmaking_stats_under_matchmaking_stats.html',1,'Oculus::Platform']]],
  ['messagewithmicrophoneavailabilitystate_167',['MessageWithMicrophoneAvailabilityState',['../class_oculus_1_1_platform_1_1_message_with_microphone_availability_state.html',1,'Oculus::Platform']]],
  ['messagewithnetsyncconnection_168',['MessageWithNetSyncConnection',['../class_oculus_1_1_platform_1_1_message_with_net_sync_connection.html',1,'Oculus::Platform']]],
  ['messagewithnetsyncsessionlist_169',['MessageWithNetSyncSessionList',['../class_oculus_1_1_platform_1_1_message_with_net_sync_session_list.html',1,'Oculus::Platform']]],
  ['messagewithnetsyncsessionschangednotification_170',['MessageWithNetSyncSessionsChangedNotification',['../class_oculus_1_1_platform_1_1_message_with_net_sync_sessions_changed_notification.html',1,'Oculus::Platform']]],
  ['messagewithnetsyncsetsessionpropertyresult_171',['MessageWithNetSyncSetSessionPropertyResult',['../class_oculus_1_1_platform_1_1_message_with_net_sync_set_session_property_result.html',1,'Oculus::Platform']]],
  ['messagewithnetsyncvoipattenuationvaluelist_172',['MessageWithNetSyncVoipAttenuationValueList',['../class_oculus_1_1_platform_1_1_message_with_net_sync_voip_attenuation_value_list.html',1,'Oculus::Platform']]],
  ['messagewithnetworkingpeer_173',['MessageWithNetworkingPeer',['../class_oculus_1_1_platform_1_1_message_with_networking_peer.html',1,'Oculus::Platform']]],
  ['messagewithorgscopedid_174',['MessageWithOrgScopedID',['../class_oculus_1_1_platform_1_1_message_with_org_scoped_i_d.html',1,'Oculus::Platform']]],
  ['messagewithparty_175',['MessageWithParty',['../class_oculus_1_1_platform_1_1_message_with_party.html',1,'Oculus::Platform']]],
  ['messagewithpartyid_176',['MessageWithPartyID',['../class_oculus_1_1_platform_1_1_message_with_party_i_d.html',1,'Oculus::Platform']]],
  ['messagewithpartyundercurrentparty_177',['MessageWithPartyUnderCurrentParty',['../class_oculus_1_1_platform_1_1_message_with_party_under_current_party.html',1,'Oculus::Platform']]],
  ['messagewithpartyupdatenotification_178',['MessageWithPartyUpdateNotification',['../class_oculus_1_1_platform_1_1_message_with_party_update_notification.html',1,'Oculus::Platform']]],
  ['messagewithpidlist_179',['MessageWithPidList',['../class_oculus_1_1_platform_1_1_message_with_pid_list.html',1,'Oculus::Platform']]],
  ['messagewithpingresult_180',['MessageWithPingResult',['../class_oculus_1_1_platform_1_1_message_with_ping_result.html',1,'Oculus::Platform']]],
  ['messagewithplatforminitialize_181',['MessageWithPlatformInitialize',['../class_oculus_1_1_platform_1_1_message_with_platform_initialize.html',1,'Oculus::Platform']]],
  ['messagewithproductlist_182',['MessageWithProductList',['../class_oculus_1_1_platform_1_1_message_with_product_list.html',1,'Oculus::Platform']]],
  ['messagewithpurchase_183',['MessageWithPurchase',['../class_oculus_1_1_platform_1_1_message_with_purchase.html',1,'Oculus::Platform']]],
  ['messagewithpurchaselist_184',['MessageWithPurchaseList',['../class_oculus_1_1_platform_1_1_message_with_purchase_list.html',1,'Oculus::Platform']]],
  ['messagewithrejoindialogresult_185',['MessageWithRejoinDialogResult',['../class_oculus_1_1_platform_1_1_message_with_rejoin_dialog_result.html',1,'Oculus::Platform']]],
  ['messagewithroom_186',['MessageWithRoom',['../class_oculus_1_1_platform_1_1_message_with_room.html',1,'Oculus::Platform']]],
  ['messagewithroominvitenotification_187',['MessageWithRoomInviteNotification',['../class_oculus_1_1_platform_1_1_message_with_room_invite_notification.html',1,'Oculus::Platform']]],
  ['messagewithroominvitenotificationlist_188',['MessageWithRoomInviteNotificationList',['../class_oculus_1_1_platform_1_1_message_with_room_invite_notification_list.html',1,'Oculus::Platform']]],
  ['messagewithroomlist_189',['MessageWithRoomList',['../class_oculus_1_1_platform_1_1_message_with_room_list.html',1,'Oculus::Platform']]],
  ['messagewithroomundercurrentroom_190',['MessageWithRoomUnderCurrentRoom',['../class_oculus_1_1_platform_1_1_message_with_room_under_current_room.html',1,'Oculus::Platform']]],
  ['messagewithroomunderviewerroom_191',['MessageWithRoomUnderViewerRoom',['../class_oculus_1_1_platform_1_1_message_with_room_under_viewer_room.html',1,'Oculus::Platform']]],
  ['messagewithsdkaccountlist_192',['MessageWithSdkAccountList',['../class_oculus_1_1_platform_1_1_message_with_sdk_account_list.html',1,'Oculus::Platform']]],
  ['messagewithsendinvitesresult_193',['MessageWithSendInvitesResult',['../class_oculus_1_1_platform_1_1_message_with_send_invites_result.html',1,'Oculus::Platform']]],
  ['messagewithsharemediaresult_194',['MessageWithShareMediaResult',['../class_oculus_1_1_platform_1_1_message_with_share_media_result.html',1,'Oculus::Platform']]],
  ['messagewithstring_195',['MessageWithString',['../class_oculus_1_1_platform_1_1_message_with_string.html',1,'Oculus::Platform']]],
  ['messagewithsystemvoipstate_196',['MessageWithSystemVoipState',['../class_oculus_1_1_platform_1_1_message_with_system_voip_state.html',1,'Oculus::Platform']]],
  ['messagewithuser_197',['MessageWithUser',['../class_oculus_1_1_platform_1_1_message_with_user.html',1,'Oculus::Platform']]],
  ['messagewithuserandroomlist_198',['MessageWithUserAndRoomList',['../class_oculus_1_1_platform_1_1_message_with_user_and_room_list.html',1,'Oculus::Platform']]],
  ['messagewithusercapabilitylist_199',['MessageWithUserCapabilityList',['../class_oculus_1_1_platform_1_1_message_with_user_capability_list.html',1,'Oculus::Platform']]],
  ['messagewithuserdatastoreupdateresponse_200',['MessageWithUserDataStoreUpdateResponse',['../class_oculus_1_1_platform_1_1_message_with_user_data_store_update_response.html',1,'Oculus::Platform']]],
  ['messagewithuserlist_201',['MessageWithUserList',['../class_oculus_1_1_platform_1_1_message_with_user_list.html',1,'Oculus::Platform']]],
  ['messagewithuserproof_202',['MessageWithUserProof',['../class_oculus_1_1_platform_1_1_message_with_user_proof.html',1,'Oculus::Platform']]],
  ['messagewithuserreportid_203',['MessageWithUserReportID',['../class_oculus_1_1_platform_1_1_message_with_user_report_i_d.html',1,'Oculus::Platform']]],
  ['mic_204',['Mic',['../class_meta_1_1_wit_ai_1_1_lib_1_1_mic.html',1,'Meta::WitAi::Lib']]],
  ['micbase_205',['MicBase',['../class_meta_1_1_wit_ai_1_1_lib_1_1_mic_base.html',1,'Meta::WitAi::Lib']]],
  ['micdebug_206',['MicDebug',['../class_meta_1_1_wit_ai_1_1_lib_1_1_mic_debug.html',1,'Meta::WitAi::Lib']]],
  ['miceditor_207',['MicEditor',['../class_meta_1_1_wit_ai_1_1_lib_1_1_mic_editor.html',1,'Meta::WitAi::Lib']]],
  ['micpermissionsmanager_208',['MicPermissionsManager',['../class_oculus_1_1_voice_s_d_k_1_1_dictation_1_1_utilities_1_1_mic_permissions_manager.html',1,'Oculus.VoiceSDK.Dictation.Utilities.MicPermissionsManager'],['../class_oculus_1_1_voice_s_d_k_1_1_utilities_1_1_mic_permissions_manager.html',1,'Oculus.VoiceSDK.Utilities.MicPermissionsManager']]],
  ['microphoneavailabilitystate_209',['MicrophoneAvailabilityState',['../class_oculus_1_1_platform_1_1_models_1_1_microphone_availability_state.html',1,'Oculus::Platform::Models']]],
  ['minmaxattribute_210',['MinMaxAttribute',['../class_o_v_r_1_1_min_max_attribute.html',1,'OVR']]],
  ['minmaxpair_211',['MinMaxPair',['../struct_oculus_1_1_interaction_1_1_min_max_pair.html',1,'Oculus::Interaction']]],
  ['minmaxpropertydrawer_212',['MinMaxPropertyDrawer',['../class_o_v_r_1_1_min_max_property_drawer.html',1,'OVR']]],
  ['minthresholdsconfig_213',['MinThresholdsConfig',['../class_oculus_1_1_interaction_1_1_poke_interactable_1_1_min_thresholds_config.html',1,'Oculus::Interaction::PokeInteractable']]],
  ['mixersnapshot_214',['MixerSnapshot',['../class_o_v_r_1_1_mixer_snapshot.html',1,'OVR']]],
  ['mixersnapshotpropertydrawer_215',['MixerSnapshotPropertyDrawer',['../class_o_v_r_1_1_mixer_snapshot_property_drawer.html',1,'OVR']]],
  ['monoinspector_216',['MonoInspector',['../class_oculus_1_1_interaction_1_1_interface_support_1_1_interface_picker_1_1_mono_inspector.html',1,'Oculus::Interaction::InterfaceSupport::InterfacePicker']]],
  ['mouselook_217',['MouseLook',['../class_mouse_look.html',1,'']]],
  ['moveatsourceprovider_218',['MoveAtSourceProvider',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_move_at_source_provider.html',1,'Oculus::Interaction::HandGrab']]],
  ['movefromtarget_219',['MoveFromTarget',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_move_from_target.html',1,'Oculus::Interaction::HandGrab']]],
  ['movefromtargetprovider_220',['MoveFromTargetProvider',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_move_from_target_provider.html',1,'Oculus::Interaction::HandGrab']]],
  ['moverelativetotarget_221',['MoveRelativeToTarget',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_move_relative_to_target.html',1,'Oculus::Interaction::HandGrab']]],
  ['movetowardstarget_222',['MoveTowardsTarget',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_move_towards_target.html',1,'Oculus::Interaction::HandGrab']]],
  ['movetowardstargetprovider_223',['MoveTowardsTargetProvider',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_move_towards_target_provider.html',1,'Oculus::Interaction::HandGrab']]],
  ['movieplayersample_224',['MoviePlayerSample',['../class_movie_player_sample.html',1,'']]],
  ['movieplayersamplecontrols_225',['MoviePlayerSampleControls',['../class_movie_player_sample_controls.html',1,'']]],
  ['multiaction_226',['MultiAction',['../class_oculus_1_1_interaction_1_1_multi_action.html',1,'Oculus::Interaction']]],
  ['multiaction_3c_20tinteractable_20_3e_227',['MultiAction&lt; TInteractable &gt;',['../class_oculus_1_1_interaction_1_1_multi_action.html',1,'Oculus::Interaction']]],
  ['multiaction_3c_20tinteractor_20_3e_228',['MultiAction&lt; TInteractor &gt;',['../class_oculus_1_1_interaction_1_1_multi_action.html',1,'Oculus::Interaction']]],
  ['multianchordelegatepair_229',['MultiAnchorDelegatePair',['../struct_o_v_r_spatial_anchor_1_1_multi_anchor_delegate_pair.html',1,'OVRSpatialAnchor']]],
  ['multiplayererroroptions_230',['MultiplayerErrorOptions',['../class_oculus_1_1_platform_1_1_multiplayer_error_options.html',1,'Oculus::Platform']]],
  ['multirequesttranscription_231',['MultiRequestTranscription',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_multi_request_transcription.html',1,'Meta::WitAi::Dictation']]],
  ['multivalueevent_232',['MultiValueEvent',['../class_meta_1_1_wit_ai_1_1_callback_handlers_1_1_multi_value_event.html',1,'Meta::WitAi::CallbackHandlers']]],
  ['mycustomscenemodelloader_233',['MyCustomSceneModelLoader',['../class_my_custom_scene_model_loader.html',1,'']]]
];
