var searchData=
[
  ['iactivestate_0',['IActiveState',['../interface_oculus_1_1_interaction_1_1_i_active_state.html',1,'Oculus::Interaction']]],
  ['iactivestatemodel_1',['IActiveStateModel',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_model.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iactivestatenodeui_2',['IActiveStateNodeUI',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_node_u_i.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iactivestatetreenode_3',['IActiveStateTreeNode',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_tree_node.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iapmanager_4',['IAPManager',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_board_game_1_1_i_a_p_manager.html',1,'Oculus::Platform::Samples::VrBoardGame']]],
  ['iapplicationdetailprovider_5',['IApplicationDetailProvider',['../interface_meta_1_1_wit_ai_1_1_data_1_1_configuration_1_1_i_application_detail_provider.html',1,'Meta::WitAi::Data::Configuration']]],
  ['iaudioeventprovider_6',['IAudioEventProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_event_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['iaudioinputevents_7',['IAudioInputEvents',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_input_events.html',1,'Meta::WitAi::Interfaces']]],
  ['iaudioinputsource_8',['IAudioInputSource',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_input_source.html',1,'Meta::WitAi::Interfaces']]],
  ['iaxis1d_9',['IAxis1D',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_axis1_d.html',1,'Oculus::Interaction::Input']]],
  ['iaxis2d_10',['IAxis2D',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_axis2_d.html',1,'Oculus::Interaction::Input']]],
  ['ibounds_11',['IBounds',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_bounds.html',1,'Oculus::Interaction::Surfaces']]],
  ['iboundsclipper_12',['IBoundsClipper',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_bounds_clipper.html',1,'Oculus::Interaction::Surfaces']]],
  ['ibutton_13',['IButton',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_button.html',1,'Oculus::Interaction::Input']]],
  ['icandidatecomparer_14',['ICandidateComparer',['../interface_oculus_1_1_interaction_1_1_i_candidate_comparer.html',1,'Oculus::Interaction']]],
  ['icandidateposition_15',['ICandidatePosition',['../interface_oculus_1_1_interaction_1_1_i_candidate_position.html',1,'Oculus::Interaction']]],
  ['iclippedsurface_16',['IClippedSurface',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['iclippedsurface_3c_20iboundsclipper_20_3e_17',['IClippedSurface&lt; IBoundsClipper &gt;',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['iclippedsurface_3c_20icylinderclipper_20_3e_18',['IClippedSurface&lt; ICylinderClipper &gt;',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['icollidersref_19',['ICollidersRef',['../interface_oculus_1_1_interaction_1_1_i_colliders_ref.html',1,'Oculus::Interaction']]],
  ['iconnection_20',['IConnection',['../interface_oculus_1_1_voice_1_1_core_1_1_bindings_1_1_interfaces_1_1_i_connection.html',1,'Oculus::Voice::Core::Bindings::Interfaces']]],
  ['icontroller_21',['IController',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_controller.html',1,'Oculus::Interaction::Input']]],
  ['icontrollerdatamodifier_22',['IControllerDataModifier',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_controller_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_23',['ICopyFrom',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20controllerdataasset_20_3e_24',['ICopyFrom&lt; ControllerDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20handdataasset_20_3e_25',['ICopyFrom&lt; HandDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20hmddataasset_20_3e_26',['ICopyFrom&lt; HmdDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icurvedplane_27',['ICurvedPlane',['../interface_oculus_1_1_interaction_1_1_i_curved_plane.html',1,'Oculus::Interaction']]],
  ['icylinderclipper_28',['ICylinderClipper',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_cylinder_clipper.html',1,'Oculus::Interaction::Surfaces']]],
  ['idatasource_29',['IDataSource',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_data_source.html',1,'Oculus::Interaction::Input']]],
  ['idictationservice_30',['IDictationService',['../interface_meta_1_1_wit_ai_1_1_dictation_1_1_i_dictation_service.html',1,'Meta::WitAi::Dictation']]],
  ['idistanceinteractor_31',['IDistanceInteractor',['../interface_oculus_1_1_interaction_1_1_i_distance_interactor.html',1,'Oculus::Interaction']]],
  ['idynamicentitiesprovider_32',['IDynamicEntitiesProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_dynamic_entities_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['ienumerablehashset_33',['IEnumerableHashSet',['../interface_oculus_1_1_interaction_1_1_collections_1_1_i_enumerable_hash_set.html',1,'Oculus::Interaction::Collections']]],
  ['ievent_34',['IEvent',['../interface_oculus_1_1_interaction_1_1_i_event.html',1,'Oculus::Interaction']]],
  ['ifeaturestatethreshold_35',['IFeatureStateThreshold',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_threshold.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethreshold_3c_20string_20_3e_36',['IFeatureStateThreshold&lt; string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_threshold.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_37',['IFeatureStateThresholds',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_3c_20fingerfeature_2c_20string_20_3e_38',['IFeatureStateThresholds&lt; FingerFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_3c_20transformfeature_2c_20string_20_3e_39',['IFeatureStateThresholds&lt; TransformFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_40',['IFeatureThresholds',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_3c_20fingerfeature_2c_20string_20_3e_41',['IFeatureThresholds&lt; FingerFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_3c_20transformfeature_2c_20string_20_3e_42',['IFeatureThresholds&lt; TransformFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifingerapi_43',['IFingerAPI',['../interface_oculus_1_1_interaction_1_1_i_finger_a_p_i.html',1,'Oculus::Interaction']]],
  ['ifingerfeaturestateprovider_44',['IFingerFeatureStateProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_finger_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifingeruseapi_45',['IFingerUseAPI',['../interface_oculus_1_1_interaction_1_1_i_finger_use_a_p_i.html',1,'Oculus::Interaction']]],
  ['igameobjectfilter_46',['IGameObjectFilter',['../interface_oculus_1_1_interaction_1_1_i_game_object_filter.html',1,'Oculus::Interaction']]],
  ['igrabbable_47',['IGrabbable',['../interface_oculus_1_1_interaction_1_1_i_grabbable.html',1,'Oculus::Interaction']]],
  ['igrabsurface_48',['IGrabSurface',['../interface_oculus_1_1_interaction_1_1_grab_1_1_grab_surfaces_1_1_i_grab_surface.html',1,'Oculus::Interaction::Grab::GrabSurfaces']]],
  ['ihand_49',['IHand',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand.html',1,'Oculus::Interaction::Input']]],
  ['ihandgrabbable_50',['IHandGrabbable',['../interface_oculus_1_1_interaction_1_1_grab_1_1_i_hand_grabbable.html',1,'Oculus::Interaction::Grab']]],
  ['ihandgrabber_51',['IHandGrabber',['../interface_oculus_1_1_interaction_1_1_grab_1_1_i_hand_grabber.html',1,'Oculus::Interaction::Grab']]],
  ['ihandgrabstate_52',['IHandGrabState',['../interface_oculus_1_1_interaction_1_1_hand_grab_1_1_i_hand_grab_state.html',1,'Oculus::Interaction::HandGrab']]],
  ['ihandgrabusedelegate_53',['IHandGrabUseDelegate',['../interface_oculus_1_1_interaction_1_1_hand_grab_1_1_i_hand_grab_use_delegate.html',1,'Oculus::Interaction::HandGrab']]],
  ['ihandskeletonprovider_54',['IHandSkeletonProvider',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand_skeleton_provider.html',1,'Oculus::Interaction::Input']]],
  ['ihandspheremap_55',['IHandSphereMap',['../interface_oculus_1_1_interaction_1_1_i_hand_sphere_map.html',1,'Oculus::Interaction']]],
  ['ihandvisual_56',['IHandVisual',['../interface_oculus_1_1_interaction_1_1_i_hand_visual.html',1,'Oculus::Interaction']]],
  ['ihmd_57',['IHmd',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hmd.html',1,'Oculus::Interaction::Input']]],
  ['iinteractable_58',['IInteractable',['../interface_oculus_1_1_interaction_1_1_i_interactable.html',1,'Oculus::Interaction']]],
  ['iinteractableview_59',['IInteractableView',['../interface_oculus_1_1_interaction_1_1_i_interactable_view.html',1,'Oculus::Interaction']]],
  ['iinteractor_60',['IInteractor',['../interface_oculus_1_1_interaction_1_1_i_interactor.html',1,'Oculus::Interaction']]],
  ['iinteractorview_61',['IInteractorView',['../interface_oculus_1_1_interaction_1_1_i_interactor_view.html',1,'Oculus::Interaction']]],
  ['ijointdeltaprovider_62',['IJointDeltaProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_joint_delta_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ijsondeserializer_63',['IJsonDeserializer',['../interface_meta_1_1_wit_ai_1_1_json_1_1_i_json_deserializer.html',1,'Meta::WitAi::Json']]],
  ['ijsonserializer_64',['IJsonSerializer',['../interface_meta_1_1_wit_ai_1_1_json_1_1_i_json_serializer.html',1,'Meta::WitAi::Json']]],
  ['ilocomotioneventbroadcaster_65',['ILocomotionEventBroadcaster',['../interface_oculus_1_1_interaction_1_1_locomotion_1_1_i_locomotion_event_broadcaster.html',1,'Oculus::Interaction::Locomotion']]],
  ['ilocomotioneventhandler_66',['ILocomotionEventHandler',['../interface_oculus_1_1_interaction_1_1_locomotion_1_1_i_locomotion_event_handler.html',1,'Oculus::Interaction::Locomotion']]],
  ['imicrophone_67',['IMicrophone',['../interface_oculus_1_1_platform_1_1_i_microphone.html',1,'Oculus::Platform']]],
  ['imovement_68',['IMovement',['../interface_oculus_1_1_interaction_1_1_i_movement.html',1,'Oculus::Interaction']]],
  ['imovementprovider_69',['IMovementProvider',['../interface_oculus_1_1_interaction_1_1_i_movement_provider.html',1,'Oculus::Interaction']]],
  ['impactaudio_70',['ImpactAudio',['../struct_oculus_1_1_interaction_1_1_impact_audio.html',1,'Oculus::Interaction']]],
  ['imusample_5ft_71',['ImuSample_t',['../struct_o_v_r_1_1_open_v_r_1_1_imu_sample__t.html',1,'OVR::OpenVR']]],
  ['indexpinchsafereleaseselector_72',['IndexPinchSafeReleaseSelector',['../class_oculus_1_1_interaction_1_1_index_pinch_safe_release_selector.html',1,'Oculus::Interaction']]],
  ['indexpinchselector_73',['IndexPinchSelector',['../class_oculus_1_1_interaction_1_1_index_pinch_selector.html',1,'Oculus::Interaction']]],
  ['inputanalogactiondata_5ft_74',['InputAnalogActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_analog_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputaxis_75',['InputAxis',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_axis.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputbutton_76',['InputButton',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_button.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputdigitalactiondata_5ft_77',['InputDigitalActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_digital_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputkey_78',['InputKey',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_key.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputmousebutton_79',['InputMouseButton',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_mouse_button.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputnodestate_80',['InputNodeState',['../struct_o_v_r_g_l_t_f_animatinon_node_1_1_input_node_state.html',1,'OVRGLTFAnimatinonNode']]],
  ['inputorigininfo_5ft_81',['InputOriginInfo_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_origin_info__t.html',1,'OVR::OpenVR']]],
  ['inputposeactiondata_5ft_82',['InputPoseActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_pose_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputskeletalactiondata_5ft_83',['InputSkeletalActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_skeletal_action_data__t.html',1,'OVR::OpenVR']]],
  ['insightpassthroughkeyboardhandsintensity_84',['InsightPassthroughKeyboardHandsIntensity',['../struct_o_v_r_plugin_1_1_insight_passthrough_keyboard_hands_intensity.html',1,'OVRPlugin']]],
  ['insightpassthroughstyle_85',['InsightPassthroughStyle',['../struct_o_v_r_plugin_1_1_insight_passthrough_style.html',1,'OVRPlugin']]],
  ['inspectorbuttonattribute_86',['InspectorButtonAttribute',['../class_oculus_1_1_interaction_1_1_inspector_button_attribute.html',1,'Oculus::Interaction']]],
  ['inspectorcommentattribute_87',['InspectorCommentAttribute',['../class_inspector_comment_attribute.html',1,'']]],
  ['inspectornoteattribute_88',['InspectorNoteAttribute',['../class_inspector_note_attribute.html',1,'']]],
  ['installedapplication_89',['InstalledApplication',['../class_oculus_1_1_platform_1_1_models_1_1_installed_application.html',1,'Oculus::Platform::Models']]],
  ['installedapplicationlist_90',['InstalledApplicationList',['../class_oculus_1_1_platform_1_1_models_1_1_installed_application_list.html',1,'Oculus::Platform::Models']]],
  ['instructions_91',['Instructions',['../class_oculus_1_1_voice_1_1_demo_1_1_u_i_shapes_demo_1_1_instructions.html',1,'Oculus::Voice::Demo::UIShapesDemo']]],
  ['interactable_92',['Interactable',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus.Interaction.Interactable&lt; TInteractor, TInteractable &gt;'],['../class_oculus_sample_framework_1_1_interactable.html',1,'OculusSampleFramework.Interactable']]],
  ['interactable_3c_20handgrabuseinteractor_2c_20handgrabuseinteractable_20_3e_93',['Interactable&lt; HandGrabUseInteractor, HandGrabUseInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20locomotionaxisturnerinteractor_2c_20locomotionaxisturnerinteractable_20_3e_94',['Interactable&lt; LocomotionAxisTurnerInteractor, LocomotionAxisTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20locomotionturnerinteractor_2c_20locomotionturnerinteractable_20_3e_95',['Interactable&lt; LocomotionTurnerInteractor, LocomotionTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20snapinteractor_2c_20snapinteractable_20_3e_96',['Interactable&lt; SnapInteractor, SnapInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20teleportinteractor_2c_20teleportinteractable_20_3e_97',['Interactable&lt; TeleportInteractor, TeleportInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactablecollisioninfo_98',['InteractableCollisionInfo',['../class_oculus_sample_framework_1_1_interactable_collision_info.html',1,'OculusSampleFramework']]],
  ['interactablecolorvisual_99',['InteractableColorVisual',['../class_oculus_1_1_interaction_1_1_interactable_color_visual.html',1,'Oculus::Interaction']]],
  ['interactabledebugvisual_100',['InteractableDebugVisual',['../class_oculus_1_1_interaction_1_1_interactable_debug_visual.html',1,'Oculus::Interaction']]],
  ['interactablegroup_101',['InteractableGroup',['../class_oculus_1_1_interaction_1_1_interactable_group.html',1,'Oculus::Interaction']]],
  ['interactablegroupview_102',['InteractableGroupView',['../class_oculus_1_1_interaction_1_1_interactable_group_view.html',1,'Oculus::Interaction']]],
  ['interactablelimits_103',['InteractableLimits',['../struct_oculus_1_1_interaction_1_1_interactable_group_1_1_interactable_limits.html',1,'Oculus::Interaction::InteractableGroup']]],
  ['interactableregistry_104',['InteractableRegistry',['../class_oculus_1_1_interaction_1_1_interactable_registry.html',1,'Oculus.Interaction.InteractableRegistry&lt; TInteractor, TInteractable &gt;'],['../class_oculus_sample_framework_1_1_interactable_registry.html',1,'OculusSampleFramework.InteractableRegistry']]],
  ['interactableset_105',['InteractableSet',['../struct_oculus_1_1_interaction_1_1_interactable_registry_1_1_interactable_set.html',1,'Oculus::Interaction::InteractableRegistry']]],
  ['interactablestateargs_106',['InteractableStateArgs',['../class_oculus_sample_framework_1_1_interactable_state_args.html',1,'OculusSampleFramework']]],
  ['interactablestateargsevent_107',['InteractableStateArgsEvent',['../class_oculus_sample_framework_1_1_interactable_1_1_interactable_state_args_event.html',1,'OculusSampleFramework::Interactable']]],
  ['interactablestatechangeargs_108',['InteractableStateChangeArgs',['../struct_oculus_1_1_interaction_1_1_interactable_state_change_args.html',1,'Oculus::Interaction']]],
  ['interactabletool_109',['InteractableTool',['../class_oculus_sample_framework_1_1_interactable_tool.html',1,'OculusSampleFramework']]],
  ['interactabletoolscreator_110',['InteractableToolsCreator',['../class_oculus_sample_framework_1_1_interactable_tools_creator.html',1,'OculusSampleFramework']]],
  ['interactabletoolsinputrouter_111',['InteractableToolsInputRouter',['../class_oculus_sample_framework_1_1_interactable_tools_input_router.html',1,'OculusSampleFramework']]],
  ['interactabletoolview_112',['InteractableToolView',['../interface_oculus_sample_framework_1_1_interactable_tool_view.html',1,'OculusSampleFramework']]],
  ['interactabletriggerbroadcaster_113',['InteractableTriggerBroadcaster',['../class_oculus_1_1_interaction_1_1_interactable_trigger_broadcaster.html',1,'Oculus::Interaction']]],
  ['interactableunityeventwrapper_114',['InteractableUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_interactable_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['interactionhandler_115',['InteractionHandler',['../class_oculus_1_1_voice_1_1_demo_1_1_interaction_handler.html',1,'Oculus::Voice::Demo']]],
  ['interactor_116',['Interactor',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20handgrabuseinteractor_2c_20handgrabuseinteractable_20_3e_117',['Interactor&lt; HandGrabUseInteractor, HandGrabUseInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20locomotionaxisturnerinteractor_2c_20locomotionaxisturnerinteractable_20_3e_118',['Interactor&lt; LocomotionAxisTurnerInteractor, LocomotionAxisTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20locomotionturnerinteractor_2c_20locomotionturnerinteractable_20_3e_119',['Interactor&lt; LocomotionTurnerInteractor, LocomotionTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20snapinteractor_2c_20snapinteractable_20_3e_120',['Interactor&lt; SnapInteractor, SnapInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20teleportinteractor_2c_20teleportinteractable_20_3e_121',['Interactor&lt; TeleportInteractor, TeleportInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactoractivestate_122',['InteractorActiveState',['../class_oculus_1_1_interaction_1_1_interactor_active_state.html',1,'Oculus::Interaction']]],
  ['interactordebugvisual_123',['InteractorDebugVisual',['../class_oculus_1_1_interaction_1_1_interactor_debug_visual.html',1,'Oculus::Interaction']]],
  ['interactorgroup_124',['InteractorGroup',['../class_oculus_1_1_interaction_1_1_interactor_group.html',1,'Oculus::Interaction']]],
  ['interactorreticle_125',['InteractorReticle',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledataghost_20_3e_126',['InteractorReticle&lt; ReticleDataGhost &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledataicon_20_3e_127',['InteractorReticle&lt; ReticleDataIcon &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledatamesh_20_3e_128',['InteractorReticle&lt; ReticleDataMesh &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledatateleport_20_3e_129',['InteractorReticle&lt; ReticleDataTeleport &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorstatechangeargs_130',['InteractorStateChangeArgs',['../struct_oculus_1_1_interaction_1_1_interactor_state_change_args.html',1,'Oculus::Interaction']]],
  ['interactorunityeventwrapper_131',['InteractorUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_interactor_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['interfaceattribute_132',['InterfaceAttribute',['../class_oculus_1_1_interaction_1_1_interface_attribute.html',1,'Oculus::Interaction']]],
  ['interfacedrawer_133',['InterfaceDrawer',['../class_oculus_1_1_interaction_1_1_interface_support_1_1_interface_drawer.html',1,'Oculus::Interaction::InterfaceSupport']]],
  ['interfacepicker_134',['InterfacePicker',['../class_oculus_1_1_interaction_1_1_interface_support_1_1_interface_picker.html',1,'Oculus::Interaction::InterfaceSupport']]],
  ['interpolationcache_135',['InterpolationCache',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_grab_pose_finder_1_1_interpolation_cache.html',1,'Oculus::Interaction::HandGrab::GrabPoseFinder']]],
  ['intersectionmaskcircle_5ft_136',['IntersectionMaskCircle_t',['../struct_o_v_r_1_1_open_v_r_1_1_intersection_mask_circle__t.html',1,'OVR::OpenVR']]],
  ['intersectionmaskrectangle_5ft_137',['IntersectionMaskRectangle_t',['../struct_o_v_r_1_1_open_v_r_1_1_intersection_mask_rectangle__t.html',1,'OVR::OpenVR']]],
  ['invite_138',['Invite',['../struct_oculus_1_1_platform_1_1_samples_1_1_vr_voice_chat_1_1_room_manager_1_1_invite.html',1,'Oculus::Platform::Samples::VrVoiceChat::RoomManager']]],
  ['inviteoptions_139',['InviteOptions',['../class_oculus_1_1_platform_1_1_invite_options.html',1,'Oculus::Platform']]],
  ['invitepanelresultinfo_140',['InvitePanelResultInfo',['../class_oculus_1_1_platform_1_1_models_1_1_invite_panel_result_info.html',1,'Oculus::Platform::Models']]],
  ['ioneeurofilter_141',['IOneEuroFilter',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20float_20_3e_142',['IOneEuroFilter&lt; float &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20quaternion_20_3e_143',['IOneEuroFilter&lt; Quaternion &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20vector3_20_3e_144',['IOneEuroFilter&lt; Vector3 &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['iovrcamerarigref_145',['IOVRCameraRigRef',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_o_v_r_camera_rig_ref.html',1,'Oculus::Interaction::Input']]],
  ['iovrmeshdataprovider_146',['IOVRMeshDataProvider',['../interface_o_v_r_mesh_1_1_i_o_v_r_mesh_data_provider.html',1,'OVRMesh']]],
  ['iovrmeshrendererdataprovider_147',['IOVRMeshRendererDataProvider',['../interface_o_v_r_mesh_renderer_1_1_i_o_v_r_mesh_renderer_data_provider.html',1,'OVRMeshRenderer']]],
  ['iovrplugininfosupplier_148',['IOVRPluginInfoSupplier',['../interface_oculus_1_1_v_r_1_1_editor_1_1_i_o_v_r_plugin_info_supplier.html',1,'Oculus::VR::Editor']]],
  ['iovrskeletondataprovider_149',['IOVRSkeletonDataProvider',['../interface_o_v_r_skeleton_1_1_i_o_v_r_skeleton_data_provider.html',1,'OVRSkeleton']]],
  ['iovrskeletonrendererdataprovider_150',['IOVRSkeletonRendererDataProvider',['../interface_o_v_r_skeleton_renderer_1_1_i_o_v_r_skeleton_renderer_data_provider.html',1,'OVRSkeletonRenderer']]],
  ['iplatformvoiceservice_151',['IPlatformVoiceService',['../interface_oculus_1_1_voice_1_1_interfaces_1_1_i_platform_voice_service.html',1,'Oculus::Voice::Interfaces']]],
  ['ipointable_152',['IPointable',['../interface_oculus_1_1_interaction_1_1_i_pointable.html',1,'Oculus::Interaction']]],
  ['ipointablecanvas_153',['IPointableCanvas',['../interface_oculus_1_1_interaction_1_1_i_pointable_canvas.html',1,'Oculus::Interaction']]],
  ['ipointableelement_154',['IPointableElement',['../interface_oculus_1_1_interaction_1_1_i_pointable_element.html',1,'Oculus::Interaction']]],
  ['iposeinputdevice_155',['IPoseInputDevice',['../interface_oculus_1_1_interaction_1_1_throw_1_1_i_pose_input_device.html',1,'Oculus::Interaction::Throw']]],
  ['ireadonlyhandskeleton_156',['IReadOnlyHandSkeleton',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_read_only_hand_skeleton.html',1,'Oculus::Interaction::Input']]],
  ['ireadonlyhandskeletonjointlist_157',['IReadOnlyHandSkeletonJointList',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_read_only_hand_skeleton_joint_list.html',1,'Oculus::Interaction::Input']]],
  ['irelativetoref_158',['IRelativeToRef',['../interface_oculus_1_1_interaction_1_1_i_relative_to_ref.html',1,'Oculus::Interaction']]],
  ['iremotedrawable_159',['IRemoteDrawable',['../interface_oculus_1_1_interaction_1_1_editor_1_1_i_remote_drawable.html',1,'Oculus::Interaction::Editor']]],
  ['irequest_160',['IRequest',['../interface_meta_1_1_wit_ai_1_1_i_request.html',1,'Meta::WitAi']]],
  ['ireticledata_161',['IReticleData',['../interface_oculus_1_1_interaction_1_1_distance_reticles_1_1_i_reticle_data.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['irigidbodyref_162',['IRigidbodyRef',['../interface_oculus_1_1_interaction_1_1_i_rigidbody_ref.html',1,'Oculus::Interaction']]],
  ['iselector_163',['ISelector',['../interface_oculus_1_1_interaction_1_1_i_selector.html',1,'Oculus::Interaction']]],
  ['iserviceevents_164',['IServiceEvents',['../interface_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_i_service_events.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['isnapposedelegate_165',['ISnapPoseDelegate',['../interface_oculus_1_1_interaction_1_1_i_snap_pose_delegate.html',1,'Oculus::Interaction']]],
  ['isurface_166',['ISurface',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['isurfacepatch_167',['ISurfacePatch',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_surface_patch.html',1,'Oculus::Interaction::Surfaces']]],
  ['iteleportarc_168',['ITeleportArc',['../interface_oculus_1_1_interaction_1_1_locomotion_1_1_i_teleport_arc.html',1,'Oculus::Interaction::Locomotion']]],
  ['itemrect_169',['ItemRect',['../class_o_v_r_1_1_audio_manager_inspector_1_1_item_rect.html',1,'OVR::AudioManagerInspector']]],
  ['itokenvalidationprovider_170',['ITokenValidationProvider',['../interface_meta_1_1_wit_ai_1_1_wit_auth_utility_1_1_i_token_validation_provider.html',1,'Meta::WitAi::WitAuthUtility']]],
  ['itrackingtoworldtransformer_171',['ITrackingToWorldTransformer',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_tracking_to_world_transformer.html',1,'Oculus::Interaction::Input']]],
  ['itranscriptionevent_172',['ITranscriptionEvent',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_event.html',1,'Meta::WitAi::Interfaces']]],
  ['itranscriptioneventprovider_173',['ITranscriptionEventProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_event_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['itranscriptionprovider_174',['ITranscriptionProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['itransformer_175',['ITransformer',['../interface_oculus_1_1_interaction_1_1_i_transformer.html',1,'Oculus::Interaction']]],
  ['itransformfeaturestateprovider_176',['ITransformFeatureStateProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_transform_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ittsdiskcachehandler_177',['ITTSDiskCacheHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_disk_cache_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittsruntimecachehandler_178',['ITTSRuntimeCacheHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_runtime_cache_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittsvoiceprovider_179',['ITTSVoiceProvider',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_voice_provider.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittswebhandler_180',['ITTSWebHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_web_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['iupdatedriver_181',['IUpdateDriver',['../interface_oculus_1_1_interaction_1_1_i_update_driver.html',1,'Oculus::Interaction']]],
  ['ivcbindingevents_182',['IVCBindingEvents',['../interface_oculus_1_1_voice_1_1_bindings_1_1_android_1_1_i_v_c_binding_events.html',1,'Oculus::Voice::Bindings::Android']]],
  ['ivelocitycalculator_183',['IVelocityCalculator',['../interface_oculus_1_1_interaction_1_1_throw_1_1_i_velocity_calculator.html',1,'Oculus::Interaction::Throw']]],
  ['ivoiceeventprovider_184',['IVoiceEventProvider',['../interface_meta_1_1_wit_ai_1_1_i_voice_event_provider.html',1,'Meta::WitAi']]],
  ['ivoicesdklogger_185',['IVoiceSDKLogger',['../interface_oculus_1_1_voice_1_1_core_1_1_bindings_1_1_interfaces_1_1_i_voice_s_d_k_logger.html',1,'Oculus::Voice::Core::Bindings::Interfaces']]],
  ['ivoiceservice_186',['IVoiceService',['../interface_meta_1_1_wit_ai_1_1_i_voice_service.html',1,'Meta::WitAi']]],
  ['ivoippcmsource_187',['IVoipPCMSource',['../interface_oculus_1_1_platform_1_1_i_voip_p_c_m_source.html',1,'Oculus::Platform']]],
  ['ivrapplications_188',['IVRApplications',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_applications.html',1,'OVR::OpenVR']]],
  ['ivrchaperone_189',['IVRChaperone',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_chaperone.html',1,'OVR::OpenVR']]],
  ['ivrchaperonesetup_190',['IVRChaperoneSetup',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_chaperone_setup.html',1,'OVR::OpenVR']]],
  ['ivrcompositor_191',['IVRCompositor',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_compositor.html',1,'OVR::OpenVR']]],
  ['ivrdrivermanager_192',['IVRDriverManager',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_driver_manager.html',1,'OVR::OpenVR']]],
  ['ivrextendeddisplay_193',['IVRExtendedDisplay',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_extended_display.html',1,'OVR::OpenVR']]],
  ['ivrinput_194',['IVRInput',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_input.html',1,'OVR::OpenVR']]],
  ['ivriobuffer_195',['IVRIOBuffer',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_i_o_buffer.html',1,'OVR::OpenVR']]],
  ['ivrnotifications_196',['IVRNotifications',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_notifications.html',1,'OVR::OpenVR']]],
  ['ivroverlay_197',['IVROverlay',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_overlay.html',1,'OVR::OpenVR']]],
  ['ivrrendermodels_198',['IVRRenderModels',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_render_models.html',1,'OVR::OpenVR']]],
  ['ivrresources_199',['IVRResources',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_resources.html',1,'OVR::OpenVR']]],
  ['ivrscreenshots_200',['IVRScreenshots',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_screenshots.html',1,'OVR::OpenVR']]],
  ['ivrsettings_201',['IVRSettings',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_settings.html',1,'OVR::OpenVR']]],
  ['ivrspatialanchors_202',['IVRSpatialAnchors',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_spatial_anchors.html',1,'OVR::OpenVR']]],
  ['ivrsystem_203',['IVRSystem',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_system.html',1,'OVR::OpenVR']]],
  ['ivrtrackedcamera_204',['IVRTrackedCamera',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_tracked_camera.html',1,'OVR::OpenVR']]],
  ['iwitbytedatareadyhandler_205',['IWitByteDataReadyHandler',['../interface_meta_1_1_wit_ai_1_1_events_1_1_i_wit_byte_data_ready_handler.html',1,'Meta::WitAi::Events']]],
  ['iwitbytedatasenthandler_206',['IWitByteDataSentHandler',['../interface_meta_1_1_wit_ai_1_1_events_1_1_i_wit_byte_data_sent_handler.html',1,'Meta::WitAi::Events']]],
  ['iwitrequestconfiguration_207',['IWitRequestConfiguration',['../interface_meta_1_1_wit_ai_1_1_i_wit_request_configuration.html',1,'Meta::WitAi']]],
  ['iwitrequestprovider_208',['IWitRequestProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_wit_request_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['iwitruntimeconfigprovider_209',['IWitRuntimeConfigProvider',['../interface_meta_1_1_wit_ai_1_1_i_wit_runtime_config_provider.html',1,'Meta::WitAi']]]
];
