var searchData=
[
  ['p2pmanager_0',['P2PManager',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_p2_p_manager.html',1,'Oculus.Platform.Samples.VrHoops.P2PManager'],['../class_oculus_1_1_platform_1_1_samples_1_1_vr_voice_chat_1_1_p2_p_manager.html',1,'Oculus.Platform.Samples.VrVoiceChat.P2PManager']]],
  ['p2pnetworkball_1',['P2PNetworkBall',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_p2_p_network_ball.html',1,'Oculus::Platform::Samples::VrHoops']]],
  ['p2pnetworkgoal_2',['P2PNetworkGoal',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_p2_p_network_goal.html',1,'Oculus::Platform::Samples::VrHoops']]],
  ['packet_3',['Packet',['../class_oculus_1_1_platform_1_1_packet.html',1,'Oculus::Platform']]],
  ['panelhmdfollower_4',['PanelHMDFollower',['../class_oculus_sample_framework_1_1_panel_h_m_d_follower.html',1,'OculusSampleFramework']]],
  ['paralleltranscripthandler_5',['ParallelTranscriptHandler',['../class_oculus_1_1_voice_1_1_demo_1_1_u_i_shapes_demo_1_1_parallel_transcript_handler.html',1,'Oculus::Voice::Demo::UIShapesDemo']]],
  ['party_6',['Party',['../class_oculus_1_1_platform_1_1_models_1_1_party.html',1,'Oculus::Platform::Models']]],
  ['partyid_7',['PartyID',['../class_oculus_1_1_platform_1_1_models_1_1_party_i_d.html',1,'Oculus::Platform::Models']]],
  ['partyupdatenotification_8',['PartyUpdateNotification',['../class_oculus_1_1_platform_1_1_models_1_1_party_update_notification.html',1,'Oculus::Platform::Models']]],
  ['passthroughbrush_9',['PassthroughBrush',['../class_passthrough_brush.html',1,'']]],
  ['passthroughcapabilities_10',['PassthroughCapabilities',['../class_o_v_r_manager_1_1_passthrough_capabilities.html',1,'OVRManager']]],
  ['passthroughcontroller_11',['PassthroughController',['../class_passthrough_controller.html',1,'']]],
  ['passthroughmeshinstance_12',['PassthroughMeshInstance',['../struct_o_v_r_passthrough_layer_1_1_passthrough_mesh_instance.html',1,'OVRPassthroughLayer']]],
  ['passthroughplayineditor_13',['PassthroughPlayInEditor',['../class_passthrough_play_in_editor.html',1,'']]],
  ['passthroughprojectionsurface_14',['PassthroughProjectionSurface',['../class_passthrough_projection_surface.html',1,'']]],
  ['passthroughstyler_15',['PassthroughStyler',['../class_passthrough_styler.html',1,'']]],
  ['passthroughsurface_16',['PassthroughSurface',['../class_passthrough_surface.html',1,'']]],
  ['pauseoninputloss_17',['PauseOnInputLoss',['../class_oculus_sample_framework_1_1_pause_on_input_loss.html',1,'OculusSampleFramework']]],
  ['perfmetrics_18',['PerfMetrics',['../class_o_v_r_system_perf_metrics_1_1_perf_metrics.html',1,'OVRSystemPerfMetrics']]],
  ['physicsgrabbable_19',['PhysicsGrabbable',['../class_oculus_1_1_interaction_1_1_physics_grabbable.html',1,'Oculus::Interaction']]],
  ['pid_20',['Pid',['../class_oculus_1_1_platform_1_1_models_1_1_pid.html',1,'Oculus::Platform::Models']]],
  ['pidlist_21',['PidList',['../class_oculus_1_1_platform_1_1_models_1_1_pid_list.html',1,'Oculus::Platform::Models']]],
  ['pinchstatemodule_22',['PinchStateModule',['../class_oculus_sample_framework_1_1_pinch_state_module.html',1,'OculusSampleFramework']]],
  ['pingresult_23',['PingResult',['../class_oculus_1_1_platform_1_1_models_1_1_ping_result.html',1,'Oculus::Platform::Models']]],
  ['pinnedarray_24',['PinnedArray',['../struct_o_v_r_plugin_1_1_pinned_array.html',1,'OVRPlugin']]],
  ['pitchremap_25',['PitchRemap',['../class_oculus_1_1_interaction_1_1_pitch_remap.html',1,'Oculus::Interaction']]],
  ['planesurface_26',['PlaneSurface',['../class_oculus_1_1_interaction_1_1_surfaces_1_1_plane_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['planesurfaceeditor_27',['PlaneSurfaceEditor',['../class_oculus_1_1_interaction_1_1_editor_1_1_plane_surface_editor.html',1,'Oculus::Interaction::Editor']]],
  ['platformdictationimpl_28',['PlatformDictationImpl',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_platform_dictation_impl.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['platformdictationsdkbinding_29',['PlatformDictationSDKBinding',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_platform_dictation_s_d_k_binding.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['platformdictationsession_30',['PlatformDictationSession',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_platform_dictation_session.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['platforminitialize_31',['PlatformInitialize',['../class_oculus_1_1_platform_1_1_models_1_1_platform_initialize.html',1,'Oculus::Platform::Models']]],
  ['platformmanager_32',['PlatformManager',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_board_game_1_1_platform_manager.html',1,'Oculus.Platform.Samples.VrBoardGame.PlatformManager'],['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_platform_manager.html',1,'Oculus.Platform.Samples.VrHoops.PlatformManager'],['../class_oculus_1_1_platform_1_1_samples_1_1_vr_voice_chat_1_1_platform_manager.html',1,'Oculus.Platform.Samples.VrVoiceChat.PlatformManager']]],
  ['platformsettings_33',['PlatformSettings',['../class_oculus_1_1_platform_1_1_platform_settings.html',1,'Oculus::Platform']]],
  ['player_34',['Player',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_player.html',1,'Oculus::Platform::Samples::VrHoops']]],
  ['playerarea_35',['PlayerArea',['../class_oculus_1_1_platform_1_1_samples_1_1_vr_hoops_1_1_player_area.html',1,'Oculus::Platform::Samples::VrHoops']]],
  ['playerlocomotor_36',['PlayerLocomotor',['../class_oculus_1_1_interaction_1_1_locomotion_1_1_player_locomotor.html',1,'Oculus::Interaction::Locomotion']]],
  ['pluginupdater_37',['PluginUpdater',['../class_oculus_1_1_interaction_1_1_plugin_updater.html',1,'Oculus::Interaction']]],
  ['point_38',['Point',['../class_o_n_s_p_propagation_material_1_1_point.html',1,'ONSPPropagationMaterial']]],
  ['pointablecanvas_39',['PointableCanvas',['../class_oculus_1_1_interaction_1_1_pointable_canvas.html',1,'Oculus::Interaction']]],
  ['pointablecanvaseventargs_40',['PointableCanvasEventArgs',['../class_oculus_1_1_interaction_1_1_pointable_canvas_event_args.html',1,'Oculus::Interaction']]],
  ['pointablecanvasmesh_41',['PointableCanvasMesh',['../class_oculus_1_1_interaction_1_1_pointable_canvas_mesh.html',1,'Oculus::Interaction']]],
  ['pointablecanvasmodule_42',['PointableCanvasModule',['../class_oculus_1_1_interaction_1_1_pointable_canvas_module.html',1,'Oculus::Interaction']]],
  ['pointablecanvasunityeventwrapper_43',['PointableCanvasUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_pointable_canvas_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['pointabledebuggizmos_44',['PointableDebugGizmos',['../class_oculus_1_1_interaction_1_1_pointable_debug_gizmos.html',1,'Oculus::Interaction']]],
  ['pointabledebugpolylinegizmos_45',['PointableDebugPolylineGizmos',['../class_oculus_1_1_interaction_1_1_deprecated_1_1_pointable_debug_polyline_gizmos.html',1,'Oculus::Interaction::Deprecated']]],
  ['pointabledebugvisual_46',['PointableDebugVisual',['../class_oculus_1_1_interaction_1_1_pointable_debug_visual.html',1,'Oculus::Interaction']]],
  ['pointableelement_47',['PointableElement',['../class_oculus_1_1_interaction_1_1_pointable_element.html',1,'Oculus::Interaction']]],
  ['pointableunityeventwrapper_48',['PointableUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_pointable_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['pointdata_49',['PointData',['../class_oculus_1_1_interaction_1_1_pointable_debug_gizmos_1_1_point_data.html',1,'Oculus::Interaction::PointableDebugGizmos']]],
  ['pointer_50',['Pointer',['../class_oculus_1_1_interaction_1_1_pointable_canvas_module_1_1_pointer.html',1,'Oculus::Interaction::PointableCanvasModule']]],
  ['pointerevent_51',['PointerEvent',['../struct_oculus_1_1_interaction_1_1_pointer_event.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_52',['PointerInteractable',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20distancegrabinteractor_2c_20distancegrabinteractable_20_3e_53',['PointerInteractable&lt; DistanceGrabInteractor, DistanceGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20distancehandgrabinteractor_2c_20distancehandgrabinteractable_20_3e_54',['PointerInteractable&lt; DistanceHandGrabInteractor, DistanceHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20grabinteractor_2c_20grabinteractable_20_3e_55',['PointerInteractable&lt; GrabInteractor, GrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20handgrabinteractor_2c_20handgrabinteractable_20_3e_56',['PointerInteractable&lt; HandGrabInteractor, HandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20pokeinteractor_2c_20pokeinteractable_20_3e_57',['PointerInteractable&lt; PokeInteractor, PokeInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20rayinteractor_2c_20rayinteractable_20_3e_58',['PointerInteractable&lt; RayInteractor, RayInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20touchhandgrabinteractor_2c_20touchhandgrabinteractable_20_3e_59',['PointerInteractable&lt; TouchHandGrabInteractor, TouchHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_60',['PointerInteractor',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20distancegrabinteractor_2c_20distancegrabinteractable_20_3e_61',['PointerInteractor&lt; DistanceGrabInteractor, DistanceGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20distancehandgrabinteractor_2c_20distancehandgrabinteractable_20_3e_62',['PointerInteractor&lt; DistanceHandGrabInteractor, DistanceHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20grabinteractor_2c_20grabinteractable_20_3e_63',['PointerInteractor&lt; GrabInteractor, GrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20handgrabinteractor_2c_20handgrabinteractable_20_3e_64',['PointerInteractor&lt; HandGrabInteractor, HandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20pokeinteractor_2c_20pokeinteractable_20_3e_65',['PointerInteractor&lt; PokeInteractor, PokeInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20rayinteractor_2c_20rayinteractable_20_3e_66',['PointerInteractor&lt; RayInteractor, RayInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20touchhandgrabinteractor_2c_20touchhandgrabinteractable_20_3e_67',['PointerInteractor&lt; TouchHandGrabInteractor, TouchHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pokeinteractable_68',['PokeInteractable',['../class_oculus_1_1_interaction_1_1_poke_interactable.html',1,'Oculus::Interaction']]],
  ['pokeinteractableeditor_69',['PokeInteractableEditor',['../class_oculus_1_1_interaction_1_1_editor_1_1_poke_interactable_editor.html',1,'Oculus::Interaction::Editor']]],
  ['pokeinteractablevisual_70',['PokeInteractableVisual',['../class_oculus_1_1_interaction_1_1_poke_interactable_visual.html',1,'Oculus::Interaction']]],
  ['pokeinteractor_71',['PokeInteractor',['../class_oculus_1_1_interaction_1_1_poke_interactor.html',1,'Oculus::Interaction']]],
  ['pollnexteventunion_72',['PollNextEventUnion',['../struct_o_v_r_1_1_open_v_r_1_1_c_v_r_system_1_1_poll_next_event_union.html',1,'OVR::OpenVR::CVRSystem']]],
  ['pollnextoverlayeventunion_73',['PollNextOverlayEventUnion',['../struct_o_v_r_1_1_open_v_r_1_1_c_v_r_overlay_1_1_poll_next_overlay_event_union.html',1,'OVR::OpenVR::CVROverlay']]],
  ['polygonalboundary2dinternal_74',['PolygonalBoundary2DInternal',['../struct_o_v_r_plugin_1_1_polygonal_boundary2_d_internal.html',1,'OVRPlugin']]],
  ['polylinegizmos_75',['PolylineGizmos',['../class_oculus_1_1_interaction_1_1_deprecated_1_1_polyline_gizmos.html',1,'Oculus::Interaction::Deprecated']]],
  ['polylinerenderer_76',['PolylineRenderer',['../class_oculus_1_1_interaction_1_1_polyline_renderer.html',1,'Oculus::Interaction']]],
  ['pose_77',['Pose',['../class_oculus_sample_framework_1_1_pose.html',1,'OculusSampleFramework']]],
  ['posedata_78',['PoseData',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_joint_delta_provider_1_1_pose_data.html',1,'Oculus::Interaction::PoseDetection::JointDeltaProvider']]],
  ['posef_79',['Posef',['../struct_o_v_r_plugin_1_1_posef.html',1,'OVRPlugin']]],
  ['posemeasureparameters_80',['PoseMeasureParameters',['../struct_oculus_1_1_interaction_1_1_grab_1_1_pose_measure_parameters.html',1,'Oculus::Interaction::Grab']]],
  ['posestatef_81',['PoseStatef',['../struct_o_v_r_plugin_1_1_pose_statef.html',1,'OVRPlugin']]],
  ['posetraveldata_82',['PoseTravelData',['../struct_oculus_1_1_interaction_1_1_hand_grab_1_1_pose_travel_data.html',1,'Oculus::Interaction::HandGrab']]],
  ['poseusesample_83',['PoseUseSample',['../class_oculus_1_1_interaction_1_1_samples_1_1_pose_use_sample.html',1,'Oculus::Interaction::Samples']]],
  ['positioninfo_84',['PositionInfo',['../struct_oculus_1_1_platform_1_1_samples_1_1_vr_board_game_1_1_game_board_1_1_position_info.html',1,'Oculus::Platform::Samples::VrBoardGame::GameBoard']]],
  ['positionpinningconfig_85',['PositionPinningConfig',['../class_oculus_1_1_interaction_1_1_poke_interactable_1_1_position_pinning_config.html',1,'Oculus::Interaction::PokeInteractable']]],
  ['pressurebreakable_86',['PressureBreakable',['../class_oculus_1_1_interaction_1_1_pressure_breakable.html',1,'Oculus::Interaction']]],
  ['pressuresquishable_87',['PressureSquishable',['../class_oculus_1_1_interaction_1_1_pressure_squishable.html',1,'Oculus::Interaction']]],
  ['product_88',['Product',['../class_oculus_1_1_platform_1_1_models_1_1_product.html',1,'Oculus::Platform::Models']]],
  ['productlist_89',['ProductList',['../class_oculus_1_1_platform_1_1_models_1_1_product_list.html',1,'Oculus::Platform::Models']]],
  ['progresscurve_90',['ProgressCurve',['../class_oculus_1_1_interaction_1_1_progress_curve.html',1,'Oculus::Interaction']]],
  ['projectile_91',['Projectile',['../class_scripts_1_1_projectile.html',1,'Scripts']]],
  ['propagationinterface_92',['PropagationInterface',['../interface_o_n_s_p_propagation_1_1_propagation_interface.html',1,'ONSPPropagation']]],
  ['properties_93',['Properties',['../class_gradle_1_1_properties.html',1,'Gradle.Properties'],['../class_meta_1_1_wit_ai_1_1_callback_handlers_1_1_value_path_matcher_property_drawer_1_1_properties.html',1,'Meta.WitAi.CallbackHandlers.ValuePathMatcherPropertyDrawer.Properties']]],
  ['purchase_94',['Purchase',['../class_oculus_1_1_platform_1_1_models_1_1_purchase.html',1,'Oculus::Platform::Models']]],
  ['purchaselist_95',['PurchaseList',['../class_oculus_1_1_platform_1_1_models_1_1_purchase_list.html',1,'Oculus::Platform::Models']]]
];
