name: Check Commit Convention
on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Verify commit messages
        run: |
          git log --pretty=format:%s --merges --no-merges --first-parent main..HEAD | grep -Evi '^(feat|fix|refact|update):.+$' > /tmp/bad-commit-messages
          if [ -s /tmp/bad-commit-messages ]
          then
            echo "Some commit messages don't follow the convention."
            echo "Commit messages:"
            cat /tmp/bad-commit-messages
            exit 1
          fi



